### ISSUE TITLE
Unable to see ldap users

### ISSUE THREAD

**Issue by VamPikmin** [owncloud/user_ldap#102]
Installed the app on Ubuntu 16.04 and OC 10.01
When I click on the Users section only the ldap users that have logged in since the upgrade are showing up

**Comment by VamPikmin** [comment]
After running the command manually
sudo -u www-data php /var/www/html/owncloud/occ user:sync "OCA\User_LDAP\User_Proxy"
They have showed up.

**Comment by Emil-G** [comment]
@VamPikmin - I saw the exact same behavior and fix. (Upgrading from 9.1.6, to 10.0.2)

**Comment by butonic** [comment]
Documented in the release notes to OC10. Closing as this works as designed.
