### ISSUE TITLE
Users not appear in user:sync

### ISSUE THREAD

**Issue by cdamken** [owncloud/user_ldap#121]
### Steps to reproduce:

1.- Assing a long ttl in the LDAP configuration:
```
 "s01ldap_cache_ttl": "6000",
```
2..- Check the users in the User Admin page
3.- Add a new user in LDAP/AD
4.- run ` sudo -u www-data php occ user:sync "OCA\User_LDAP\User_Proxy"`
5.- No new users are found.

Workaround: reduce the time from the TTL

@butonic @tomneedham @jvillafanez

**Comment by cdamken** [comment]
Also does not work while removing the users from LDAP/AD

**Comment by jvillafanez** [comment]
This is the expected behaviour. The user:sync command will use the ldap app to fetch the users. If the ldap is using caching, the results it will return will be bound to whatever is in the cache, or whatever the ldap app is using with it.

**Comment by cdamken** [comment]
> This is the expected behaviour.

really? 

The expected behavior __should__ remove the cache before the user:sync runs, to get a clean sync. 

The TTL is only needed for group updates and not anymore for users.

**Comment by jvillafanez** [comment]
Ok, fair enough. It should be possible to remove / bypass the cache for that request.

**Comment by cdamken** [comment]
@jvillafanez Thanks a lot!

**Comment by butonic** [comment]
I am working on a fix for email sync. that involves touching this. assigning myself

**Comment by PVince81** [comment]
fix seems far from ready, move to "planned" for the next release ?

**Comment by butonic** [comment]
master no longer uses caching for user sync
