### ISSUE TITLE
Email should be set for users when log in for the 1st time

### ISSUE THREAD

**Issue by davitol** [owncloud/user_ldap#128]
using OC 10.0.3.RC1 version

With an LDAP backend with users with mail field

```
# aaliyah_adams, people, owncloudqa.com
dn: uid=aaliyah_adams,ou=people,dc=owncloudqa,dc=com
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
cn: aaliyah
sn: adams
userPassword:: e1NTSEF9YWppZkFtckxIeExvcm0yOUdoWHBmYzdkU3Zpa2VzS2Q=
uid: aaliyah_adams
displayName: aaliyah adams
mail: owncloudsg@gmail.com
```

and setting 'mail' in mail field in advanced tab of LDAP wizard

when we log in with our LDAP user, no email address is set
![screen shot 2017-09-14 at 09 44 59](https://user-images.githubusercontent.com/10596560/30420086-cfe5da28-9938-11e7-920c-c3e718ebbffe.png)

After running command: 
```
sudo -u www-data ./occ user:sync 'OCA\User_LDAP\User_Proxy'
```

The email appears

![screen shot 2017-09-14 at 09 48 36](https://user-images.githubusercontent.com/10596560/30420133-eef78c4a-9938-11e7-9604-0dfe46ef0611.png)

**Comment by PVince81** [comment]
cc @jvillafanez

**Comment by butonic** [comment]
please try with https://github.com/owncloud/user_ldap/pull/125

**Comment by davitol** [comment]
> please try with #125

@butonic I have tried with that PR and it solves the issue.
Note: Only tested this issue, not a complete test of the PR
