### ISSUE TITLE
Config Delete not possible, argument can be ""

### ISSUE THREAD

**Issue by voroyam** [owncloud/user_ldap#129]
https://github.com/owncloud/user_ldap/blob/89ec7e7e661780d213de8432b4e442f49fdbf4c9/lib/Command/DeleteConfig.php#L51

configID was by default "" in older setups, so the configs can't get deleted.

``` 
> occ ldap:delete-config ""

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Not enough arguments (missing: "configID").             
                                                          

ldap:delete-config <configID>

```

Maybe we need to provide a script to migrate empty configIDs ?

**Comment by felixboehm** [comment]
Related PR https://github.com/owncloud/user_ldap/pull/7

**Comment by felixboehm** [comment]
Or we automatically "repair" the configIDs during update?

**Comment by tomneedham** [comment]
with master I get 
<img width="781" alt="screen shot 2017-09-27 at 14 55 15" src="https://user-images.githubusercontent.com/660805/30914407-ea3aca22-a393-11e7-87f5-af423dc52519.png">

**Comment by felixboehm** [comment]
cool. That came with PR #7  ?
Repair empty configIDs possible?

**Comment by tomneedham** [comment]
No, I just used master, no additional PR - and I was able to delete the empty config.

I made an attempt at repairing old configs here, still testing/dev https://github.com/owncloud/user_ldap/pull/130

**Comment by voroyam** [comment]
Deletion of config IDs without a number works, closing
