### ISSUE TITLE
ldap command is not available during update 9.1 to 10

### ISSUE THREAD

**Issue by voroyam** [owncloud/user_ldap#134]
1. install owncloud 9.1 with ldap configuration for ldap server 1
2. untar owncloud 10.0.3
3. occ ldap:set-config to set new ldap server 2 config
4. update

breaks at step 3.

Important: we want to execute step 3 before step 4.

command line output:

```
Fixing data perms...
hallo
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
user_ldap enabled
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.          
                                                                  

Upgrading server database...
```

**Comment by voroyam** [comment]
easy steps to reproduce:
1. setup ownCloud 10.0.3 with ldap app
2. check occ -> ldap commands available
3. edit config.php and set 'version' => '10.0.2',
4. occ command asks to update, ldap commands not available

**Comment by tomneedham** [comment]
Commands are unavailable during upgrades as we do not load the apps. This will have to be implemented as a migration if it is necessary. See #130 for the migration that is WIP. I need to better understand the requirement to edit configurations before an upgrade? Why can this not be done after upgrade? The server will still be in maintenance mode.

**Comment by tomneedham** [comment]
If you want to upgrade ldap configuration before the upgrade - this should be done before untarring the OC10 sourcecode - one we have new source in place the next step is upgrading - no other option here

**Comment by patrickjahns** [comment]
Instead of calling ldap:set-config you can try setting the config manually for ldap with `occ config:app:set user_ldap ....`

Example:
```
me@acd48c69c4e2:/var/www/owncloud# sudo -u www-data php occ config:app:set user_ldap s01use_memberof_to_detect_membership --value="test_me"
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Config value s01use_memberof_to_detect_membership for app user_ldap set to test_me

me@acd48c69c4e2:/var/www/owncloud# sudo -u www-data php occ config:app:get user_ldap s01use_memberof_to_detect_membership
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
test_me
```

This is usable for the appliance - but won't provide an programatic/autmatic path since:
- app commands are only available after an upgrade
- application migrations can only be executed after the core has been upgraded

**Comment by patrickjahns** [comment]
Closing:

1) When wanting to change the configuration it is recommended to do this before attempting the upgrade

2) If for any reason, it is not possible to run the commands in the old instance before the upgrade - use `occ app:config:set user_ldap` - but keep in mind that the values are not camel case but snake case
