### ISSUE TITLE
Test results for user_ldap release/0.10.0

### ISSUE THREAD

**Issue by davitol** [owncloud/user_ldap#150]
Test results LDAP feature for 10.0.1.

LDAP backends for testing:

#### OpenLDAP:

https://github.com/owncloud/docker-servers/tree/owncloud-openldap

#### occ commands
| Test Case                                | Expected Result                          | Result         | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- |
| **ldap:test-config**  |  |                 |
| Run occ command ```ldap:test-config``` with a valid configID| Access fine | ✅    |    ./occ ldap:test-config ''    It is needed to pass as configID an empty string. It should be improved https://github.com/owncloud/user_ldap/issues/89      |
| Run occ command ```ldap:test-config``` with a wrong host (the host changed from a valid configuration) | ERROR: configuration valid but bind failed | ✅  | It is shown ```[OC\ServerNotAvailableException]``` Lost connection to LDAP server.```                 |
| Run occ command ```ldap:test-config``` with empty password | ERROR: wrong configuration | ✅  |                 |
| Run occ command ```ldap:test-config``` with invalid configID | ERROR: Invalid configID | ✅  |                 |
| **ldap:show-config** |  |  |                 |
| Run occ command ```ldap:show-config``` with no parameters | Show all configurations available | ✅  |                 | https://github.com/owncloud/user_ldap/issues/89
| Run occ command ```ldap:show-config``` with valid configID | Show only the specified configuration | ✅  |                 |
| Run occ command ```ldap:show-config``` with invalid configID | ERROR: Invalid configID | ✅  |                 |
| Run occ command ```ldap:show-config``` with show-password flag | ldapAgentPassword shows the password in the result | ✅  |                 |
| Run occ command ```ldap:show-config``` without show-password flag | ldapAgentPassword hides the password in the result (uses “****”) | ✅ |                 |
| **ldap:set-config** |  | |                 |
| Run occ command ```ldap:set-config``` with invalid configID| ERROR: Invalid configID | ✅  |                 |
| Run occ command ```ldap:set-config``` with valid configID| The config is set | ✅  |   sudo -u www-data ./occ ldap:set-config '' ldapPort 390 --> does not return any message confirming the change; https://github.com/owncloud/core/issues/14034              |
| **ldap:search** |  | |                 |
| Run occ command ```ldap:search``` with valid configuration and no params (just the search one) | Show results (currently 15 or less) | ✅ |                 |
| Run occ command ```ldap:search``` with valid configuration and longer limit | Show results | ✅ |     https://github.com/owncloud/core/issues/15796            |
| Run occ command ```ldap:search``` with offset multiple of limit (both positive) | Show results | ✅ |                 |
| Run occ command ```ldap:search```  name (default configuration) | Show filtered results | ✅  |                 |
| Run occ command ```ldap:search``` name (fixed configuration – added “displayName” and/or other attributes in the User Search Attributes field in the wizard) | Show filtered results | ✅  |                 |
| Run occ command ```ldap:search``` group (fixed configuration – added “displayName” and/or other attributes in the Group Search Attributes field in the wizard) |  Show filtered results | ✅  |                 |
| Run occ command ```ldap:search```  Group without search | Show groups (currently 15 or less) | ✅  | 
| **ldap:check-user** |  | |                 |
| Run occ command ```ldap:check-user``` with a good oC user id | Show success message | ✅  | 
| Run occ command ```ldap:check-user``` with a wrong oC user id | ERROR: ldap user not recognized | ✅  | 
| Run occ command ```ldap:check-user``` with a good oC user id + 1 disabled configuration | ERROR: Cannot check user existance | ✅  | 
| Run occ command ```ldap:check-user``` Good oc user id + 1 disabled configuration (another one active) + force option| Success message | ✅  | 
| Run occ command ```ldap:check-user``` Good oc user id + all disabled configuration + force option; then enable the configuration and recheck | Success message | ✅  | 
| **ldap:create-empty-config** |  | |                 |
| Run occ command ```ldap:create-empty-config```  | Creates an empty LDAP configuration | ✅  | 
| **ldap:delete-config** |  | |                 |
| Run occ command ```ldap:delete-config```  | Deletes an existing LDAP configuration | ✅  | 
| **ldap:show-remnants** |  | |                 |
| Run occ command ```ldap:show-remnants```  | shows which users are not available on LDAP anymore, but have remnants in ownCloud | :warning: 🚧  | https://github.com/owncloud/user_ldap/pull/85 removes offline user and remnants table
| **ldap:update-group** |  | |                 |
| Run occ command ```ldap:update-group```  | Update the specified group membership information stored locally |  🚧 | https://github.com/owncloud/user_ldap/issues/88
 

**Scenarios added for this version:**

Testing Scenarios

This PR changes the way that we query LDAP for metadata - both through user:sync and on login. For this release, we must check that the metadata is correctly updated through both of these code paths. The following scenarios should be tested:

Both through user:sync and on login

- [x] User that doesnt exist anymore on LDAP
- [ ] User that has missing critical attributes (like email, or displayname)
- [x] User that has crazy quota attributes (0, null, false, true, f92ensfswewf)
- [x] User that has multi value attributes (mail) Tested with mobile that is the quota field. 2 values and the one taken into account is the first one 
- [x] User that has a multi value attribute as user search attribute (should all be loaded into the terms table)

**Apply LDAP quota**

Expected behaviour:

- If both LDAP quota field and default LDAP quota are set:
    - [x] if the user has a value for the LDAP quota attribute, try to use that value as quota
    - [ ] if the user doesn't have a value for the LDAP quota attribute or the value can't be parsed correctly, use the default LDAP quota. https://github.com/owncloud/user_ldap/issues/153
    - [x] if the user doesn't have a value for the LDAP quota attribute or the value can't be parsed correctly, and the default LDAP quota can't be parsed correctly, use the ownCloud's default quota.
    If the LDAP quota field is empty and the default LDAP quota is set:
    - [x] go through the above case and consider the user doesn't have the LDAP quota attribute set.
    If the LDAP quota field isn't empty and the LDAP default quota isn't set:
    - [x] if the user has a value for the attribute, try to use that value as quota.
    - [x] if the user doesn't have a value for the attribute do not change anything. This usually means that the ownCloud's default quota will be used. If the user's quota has a previous value, that value will be kept
    - [x] If neither the LDAP quota field nor the default LDAP quota is set, keep the current quota.
- Additional changes
    - [x] Explictly support "default" and "none" as valid values for the LDAP quota, both as default LDAP quota and as value for the attribute.
    - [x] Check that logs are created to troubleshoot weird quota strings.

Notes:

    Even if the user "uses" the default LDAP quota, that value will be effectively set as quota. If the admin remove the default LDAP quota at a later time, the previous default LDAP quota might still be used by other users.
    Changes in the quota aren't applied uniformly. They depend on when the user data is fetched from the LDAP. If you set a default LDAP quota value "A", then you change it to "B" and finally change it again to "C", quota values for different users might be "A", "B" or "C" at some point. It's expected that when you access to the user data (or the user logs in) the quota is applied correctly. However, keep in mind that there are some cases (check above) where the quota isn't changed, which will result in unexpected values for the quota.

**Comment by tomneedham** [comment]
I added one line to the test scenarios in the release ticket: Test an existing SAML user to see if their values are updated on login

I think this may be a bug at the moment.

**Comment by cdamken** [comment]
please check if 2 or more identical LDAP servers are configured

**Comment by davitol** [comment]
Test Case | Expected Result | Result | Related Comment
-- | -- | -- | --
Setup and configure 2 LDAP servers correctly | Users from both servers are visible and can login | ✅  |  
Setup and configure 2 LDAP servers correctly, shutdown / disconnect one of them | Users from one server (the one that is up) are visible and can login | ❌  |  https://github.com/owncloud/user_ldap/issues/48
Setup and configure 2 LDAP servers correctly, making sure that at  least one user is “shared” in both servers (uid and display name are the  same, with different password) | Both users can login in their respective accounts | 🚧 |  
Setup and configure 2 LDAP servers correctly, making sure that at  least one user is “shared” in both servers (uid and display name are the  same, with different password), and change in the LDAP wizard the  internal username to “uid” (to force a collision) | Both users can login to their respective accounts | 🚧 |  
Setup and configure 2 LDAP servers correctly, making sure that at  least one user is “shared” in both servers (uid and display name are the  same, an also with the same password) | Both users can login in to their respective accounts | ❓ |  
Setup a Backup (Replica) Host, a Backup (Replica) Port and Disable/Shutdown the Main Server | The replica should be used instead of the main server | 🚧 |

**Comment by davitol** [comment]
https://github.com/owncloud/user_ldap/issues/150#issuecomment-347605621

@cdamken Do you mean two identical configurations in the LDAP wizard?

The result is that users are available and they are not duplicated in the accounts table. If this is not the scope of your question do not hesitate to comment again.

**Comment by davitol** [comment]
#### Test LDAP properties

 Test Case                                | Expected Result                          | Result         | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- |
| **LDAP Home Attribute**  |   | 🚧  | 
| **email** Set a field as mail in advanced tab| Check that the mails are set with ther right backend information in personal page for LDAP users  | 🚧  |  |
|**avatar** Login with a user with an avatar field set in LDAP backend | The avatar is shown instead of the username  |  🚧 | |
|**nested group** In advanced tab , check nested groups checkbox |  In users page the nested group should appear with all the users of the subgroup | 🚧  | 
|**internalUserAttribute** In expert tab , set an attribute as Internal Username|  The attribute is now used as internal Username | 🚧
