### ISSUE TITLE
If LDAP quota can't be parsed correctly, it should be used the ownCloud's default quota.

### ISSUE THREAD

**Issue by davitol** [owncloud/user_ldap#153]
**Steps to reproduce:**

1. As admin set up an LDAP config with no value set in Quota Default.
2. Log in with an LDAP user  and check that the quota is the oC Default quota
3. As admin set Quota Default field with the value "@#00p"
4. Log in with an LDAP user  and check the quota.

**Expected behavior**

The quota should be oC Default quota or the previous value set

**Current behavior**

The quota is set to "0 B de 0 B (0 %)"

```
{"reqId":"rC360uIqkapATgCuWwvF","level":0,"time":"2017-11-27T11:13:09+00:00","remoteAddr":"85.57.168.79","user":"aaliyah_beer_6457","app":"user_ldap","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"using quota <@#00p> for user <aaliyah_beer_6457>"}
{"reqId":"57ZlyMxDgfT6A6pd4pJ1","level":0,"time":"2017-11-27T11:18:08+00:00","remoteAddr":"85.57.168.79","user":"aaliyah_beer_6457","app":"user_ldap","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"No LDAP quota attribute configured"}
```

**LDAP app version:** 

release/0.10.0

**Comment by PVince81** [comment]
There was work on LDAP quota recently, not sure if related ? @butonic @jvillafanez

**Comment by butonic** [comment]
Uses cores \OC_Helper::computerFileSize(). Which is implemented different from the js JS counterpart.

**Comment by butonic** [comment]
@davitol @PVince81 reopen in core and close here?

**Comment by jvillafanez** [comment]
I think the quota change is in the LDAP wizard. LDAP wizard -> advanced tab -> other attributes (?) -> default quota.

Previous fixes were for the case where LDAP app updates the quota of the user, but I guess the problem here is when the sync service fetches the quota from LDAP in order to update.

**Comment by davitol** [comment]
Test Case | Expected Result | Result | Related Comment
-- | -- | -- | --
Setup and configure 2 LDAP servers correctly | Users from both servers are visible and can login | 🚧 |  
Setup and configure 2 LDAP servers correctly, shutdown / disconnect one of them | Users from one server (the one that is up) are visible and can login | 🚧 |  
Setup and configure 2 LDAP servers correctly, making sure that at  least one user is “shared” in both servers (uid and display name are the  same, with different password) | Both users can login in their respective accounts | 🚧 |  
Setup and configure 2 LDAP servers correctly, making sure that at  least one user is “shared” in both servers (uid and display name are the  same, with different password), and change in the LDAP wizard the  internal username to “uid” (to force a collision) | Both users can login to their respective accounts | 🚧 |  
Setup and configure 2 LDAP servers correctly, making sure that at  least one user is “shared” in both servers (uid and display name are the  same, an also with the same password) | Both users can login in to their respective accounts | ❓ |  
Setup a Backup (Replica) Host, a Backup (Replica) Port and Disable/Shutdown the Main Server | The replica should be used instead of the main server | 🚧 |

**Comment by butonic** [comment]
Yes, this is about the default quota on the advanced tab. Raised https://github.com/owncloud/user_ldap/issues/154 to track checking that value.

This issue is about the sync not preventing wrong quota values, which actually is a core issue

**Comment by jvillafanez** [comment]
Check also https://github.com/owncloud/user_ldap/pull/64#issue-214076274 , specially the following statement:
> Explictly support "default" and "none" as valid values for the LDAP quota, both as default LDAP quota and as value for the attribute (not sure if it was supported before).

We have to keep the same behaviour.
