### ISSUE TITLE
Show config command broken

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#16]
### Steps
1. Setup LDAP with the web UI
1. Run show-config command without arguments:

### Expected
Displays a list of config ids.

### Actual
No config ids shown:

```
± % occ ldap:show-config
                                                                  
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The helper "table" is not defined.                              
                                                                  

ldap:show-config [--show-password] [--] [<configID>]
```

This is with core master 3ee5d6f3d66a63801a65700cd25badb484839528

This is quite critical because it makes it impossible to provide any such info for bug reports and I seem to be unable to guess the config id. I looked at oc_appconfig and didn't find anything.
Passing `""` or `0` or `1` or `localhost` also didn't work. So no idea how the config id is supposed to look like.

**Comment by DeepDiver1975** [comment]
This is because of the symfony console update.

**Comment by PVince81** [comment]
so the symfony has become dissonant ? :wink:

**Comment by PVince81** [comment]
Other commands broken as well like `ldap:show-remnants`.

Setting as critical as this makes LDAP CLI unusable.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/user_ldap/pull/24
