### ISSUE TITLE
[Short term] Improve config UI

### ISSUE THREAD

**Issue by pmaier1** [owncloud/user_ldap#181]
**Story, context and use cases**

- Goal: UI improvements to prevent admins from unwillingly changing settings leading to breaking an active LDAP config.
- Related
  - https://github.com/owncloud/user_ldap/issues/27
  - https://github.com/owncloud/user_ldap/issues/86

## Product design concept

- Configuration lock/unlock + warning message
- Expert tab: 
  - Give a very clear description with background stories on 'Expert' tab why the settings have been removed and that these values can only be changed by occ commands.
  - Remove all settings on expert tab

## Technical concept

TBD

@felixboehm @butonic @felixheidecke

**Comment by pmaier1** [comment]
https://github.com/owncloud/user_ldap/pull/210

**Comment by felixboehm** [comment]
I would prefer to close this and start https://github.com/owncloud/user_ldap/issues/182
