### ISSUE TITLE
User Manager loses attributes when cache is full

### ISSUE THREAD

**Issue by svengit** [owncloud/user_ldap#184]
The user manager uses a CappedMemoryCache with the default size of 512 elements to cache users:
https://github.com/owncloud/user_ldap/blob/29b2e4e1832e3fee3b34d67fab5ba5afe9cc4fd6/lib/User/Manager.php#L107-L108

When getting the user data later, for example the displayName

https://github.com/owncloud/user_ldap/blob/29b2e4e1832e3fee3b34d67fab5ba5afe9cc4fd6/lib/User_LDAP.php#L239-L245

cache misses are not handled in any way and the corresponding user fields will just stay empty in Owncloud.

As I understand it there are 3 solutions to this problem:
 1. Don't use a cache as a data storage. Caches lose data by design
 1. handle cache misses properly. Instead of returning false, the entry should be refetched
 1. (quick and dirty): increase the cache size (dynamically before adding any elements) to make sure all users fit

**Comment by svengit** [comment]
@butonic 


1. maybe you could force a maximum ldap chunk size then and set an appropriate capacity for the cache
1. this seems to be the only proper solution
1. This does not seem to work:

    sudo -u apache php /var/www/owncloud/occ ldap:show-config | grep -i pagingsize
    | ldapPagingSize                | 500 

Apart from that I don't think it's a good idea to rely on a user setting not getting changed. At least the code should then get the paging size and use it for the size of `CappedMemoryCache`.


> but first of all: what is the problem that you see? getDisplayname of the ldap backend is only called when syncing users or during login.

We are using OC core 10.0.3.3 and LDAP Integration 0.10.0.
Users need to be synced in a cron job to reflect changes to the directory without having to force users to log in  (e.g. a new employee started, hasn't logged in but his account needs to be available for sharing). Right now ~250 users have empty names/mails whenever the cron job ran. We also had a problem with disabled accounts in OC where the LDAP user was active all the time (I don't know if that is related at all).

I assume that `occ user:sync` fetches all user accounts from LDAP first (respecting ldap chunk size) and puts them all into the cache. Only then it starts syncing them with the OC database. I did not look at the code for this and can't be sure.

**Comment by butonic** [comment]
We did a *lot* of work on the sync logic recently: https://github.com/owncloud/core/pull/29669. That PR is for master, but for stable10 we added a workaround to user_ldap 0.10.0. It requires oc 10.0.5 to work. Please update core to 10.0.7. It should fix this issue: https://github.com/owncloud/user_ldap/pull/157#issuecomment-350685048

Reopen if it still is a problem

**Comment by svengit** [comment]
Thanks, we'll try it out!

**Comment by butonic** [comment]
oh and regarding
> I assume that occ user:sync fetches all user accounts from LDAP first (respecting ldap chunk size) and puts them all into the cache. Only then it starts syncing them with the OC database. I did not look at the code for this and can't be sure.

That was the old logic. But the code was horribly inefficient. See https://owncloud.org/news/owncloud-refactored-ldap-app-brings-significantly-improved-sync-performance/ for details. Now the code fetches a page from ldap. Caches the results so that core can update the account table for these 500 users without having to query ldap again. Then iterates over the pages.

If it still is an issue please include your ldap config when reopening.

Thx!
