### ISSUE TITLE
core tests that test auto-completing do not work correctly

### ISSUE THREAD

**Issue by individual-it** [owncloud/user_ldap#229]
UI tests from core in `tests/acceptance/features/webUISharingAutocompletion/shareAutocompletion.feature` do not work correctly here because the user database does not get synced before running the tests.

**Comment by phil-davis** [comment]
Added to the sprint so we notice this and at leats have a look to see if this is still "a thing"

**Comment by phil-davis** [comment]
There is current work on removing the fixed ldif file used in LDAP tests and creating/syncing users and groups on-the-fly. Likely that will fix this issue.

**Comment by kiranparajuli589** [comment]
Latest drone reports: 
https://drone.owncloud.com/owncloud/core/23091/90/15
https://drone.owncloud.com/owncloud/user_ldap/2191/156/18

**Comment by phil-davis** [comment]
The `webUISharingAutocompletion/shareAutocompletion.feature` tests are running and passing in `user_ldap` - great!

@individual-it close this issue?

**Comment by individual-it** [comment]
@kiranparajuli589 @dpakach what was the setting to make it pass?

**Comment by dpakach** [comment]
We need to have `'user_ldap.enable_medial_search' => true,` setting enabled in some of the test cases but other than that everything works. The failing tests are skipped [here](https://github.com/owncloud/core/pull/36854/files) .
