### ISSUE TITLE
Unable to change Profile picture when LDAP directory has none

### ISSUE THREAD

**Issue by linkp** [owncloud/user_ldap#231]
### Steps to reproduce

1. Sign in with LDAP account on an LDAP directory that does not provide profile pictures
2. Navigate to Settings/General
3. Attempt to add profile picture

### Expected behavior:

1. Click button
2. Upload image file
3. Crop
4. Save file
5. Enjoy fancy new profile picture

### Actual behavior

1. There is no option to upload profile picture

### Additional information

"Picture provided by original account" in displayed under generic letter avatar
LDAP directory (JumpCloud in my instance) does not provide a means of including profile pictures

### Versions

OS: Debian GNU/Linux 9.4 (stretch)
Package: ownCloud Build Service stable (10.0.7-1.1)

**Comment by patrickjahns** [comment]
Can you please provide more information on your configuration? What version of the user_ldap app are you using?

**Comment by linkp** [comment]
I only show 1 version available in the marketplace, 0.10.0, which is what I have installed.

**Comment by ronbailer** [comment]
Same problem with OC 10.0.8 and LDAP 0.11.0. 

Users who had avatar sets when we used local accounts (before LDAP migration) keep the images but cannot change them.

Looks like all that's left to do is add functionality to the interface.

**Comment by jvillafanez** [comment]
https://github.com/owncloud/user_ldap/pull/256 should fix the problem. The expected behaviour with the PR is described below:
* A user without avatar in LDAP can add his own avatar.
* A user with an avatar in LDAP cannot set his own avatar.
* A user with or without avatar will be updated to the one from LDAP if it's added/changed.

This is expected to come with LDAP post-0.11.0 (0.12.0 maybe?)

**Comment by linkp** [comment]
The expected custom avatar functionality has been restored in v 0.12.0 published on 4 Nov 2018.

As noted in the the comments in #256, difficulty using it may occur due to a CSS overlap problem in OC Core covering the clickable are of the avatar buttons..
