### ISSUE TITLE
LDAP 0.12.0 release

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#252]
Note: unsure if this should be major or minor. Settled on major for now as I expect more changes.

### Reason
- [x] display name fix: https://github.com/owncloud/user_ldap/commit/eb6a3fd5cdfec7e50c5a3422ee6fbc1d6197fca7
- [x] Don't throw exception when user not found on ldap during login: https://github.com/owncloud/user_ldap/pull/269
- ~~Group OU Fixes https://github.com/owncloud/user_ldap/pull/248~~
- [x] store samaccountname in preferences https://github.com/owncloud/user_ldap/pull/254
- [x] Restore Avatar behavior https://github.com/owncloud/user_ldap/pull/256

### QA
- [x] Create release branch release-0.12.0
- [x] Create "0.12.0 Testplan" @davitol https://github.com/owncloud/user_ldap/issues/296
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Documentation
- [ ] Changes in the docs needed?

### Build & Marketplace release

- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version'
- [x] Create github tag for '$version'
- [x] Build and sign tarball from github tag '$version'
- [x] Upload to marketplace
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to `master`

### Specifics

- Open tickets before QA can start
- Other specifics for app release

**Comment by PVince81** [comment]
@tomneedham @butonic do you see any additional things to ship or should we just ship that one fix ?

**Comment by PVince81** [comment]
@tomneedham @butonic can we make a cut and release what we have if the remaining tickets/PRs cannot be solved in the next days ?

**Comment by PVince81** [comment]
we already have enough items and the samaccountname was merged. I suggest to release what we have and remove the unfinished "group OU fixes" https://github.com/owncloud/user_ldap/pull/248

if there is no objection I'll move forward with the release process

**Comment by PVince81** [comment]
changelog update PR is here, please check it: https://github.com/owncloud/user_ldap/pull/293

**Comment by mmattel** [comment]
Would be greate to get https://github.com/owncloud/user_ldap/pull/237 (Jump over invalid quota message if quota isn't provided) in

**Comment by PVince81** [comment]
not critical enough to stop the release train as it already reached QA station

**Comment by mmattel** [comment]
sad, but I understand,
if it slips into by chance... 😄

**Comment by PVince81** [comment]
0.12.0 is out: https://marketplace.owncloud.com/apps/user_ldap

will prepare another release ticket for 0.13.0 for upcoming changes
