### ISSUE TITLE
Configuration Active in the WebUI buggy

### ISSUE THREAD

**Issue by voroyam** [owncloud/user_ldap#255]
If I want to disable my LDAP configuration by un checking the check box "Configuration Active" the check box get's checked when I reload the page.

Edit: Not the same, but in the same Area.

If you don't enter a backup host port - you will get an error "Could not set required LDAP Protocol version" which is not helpful at all.

There has to be a check when entering backup host/port.

**Comment by phil-davis** [comment]
"good" to know - I was having trouble "disabling" my LDAP settings in testing the other day.
I will make a note to myself to try again tomorrow when I am running 10.0.9RC3 tests, and look more carefully at what happens.
