### ISSUE TITLE
LDAP Plugin stops after Importing first user

### ISSUE THREAD

**Issue by V1TA5** [owncloud/user_ldap#26]
Hi,
the LDAP Plugin stops for me after Importing the first User.
It shows only one found in the user tab of the wizard but finds additional in the login tab if their username is entered in the test field.

**my user query:** (&(objectclass=inetOrgPerson)(memberof=cn=nasusers,ou=groups,dc=lab))

**my login query:** (&(objectclass=inetOrgPerson)(memberof=cn=nasusers,ou=groups,dc=lab)(uid=%uid))

**group query:** (&(|(objectclass=organizationalUnit))) 

**my structure:** 

- Members are allowed to have owncloud accounts: cn=nasusers;ou=groups;dc=lab
- uid object path: ou=people,o=employees,dc=lab
- user groups (example group): ou=IT,o=lablicate,o=employees,dc=lab

Attempts by the friendly irc channel folks to find the problem failed.
(It seems my entries are ok and they do work wirth other ldap enabled services)

**Comment by PVince81** [comment]
Please use the issue template from https://raw.githubusercontent.com/owncloud/core/master/issue_template.md and tell us about which ownCloud version you use, what LDAP server, etc

**Comment by V1TA5** [comment]
im getting 404 on that link.
My Version is ownCloud 8.2.8 (production)

**Comment by Kawohl** [comment]
Will fix the link.

Here is a copy of the template:

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Kawohl** [comment]
https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md is the correct link

**Comment by V1TA5** [comment]
**Steps to reproduce**

1. setup ldap server with same structure as in first post
2. add querys (from first post) into ldap wizzard
3. try importing users or test usernames on login page
Expected behaviour

**Tell us what should happen**
It should show more than 1 user on the user tab and import all of them

**Actual behaviour**

- Only shows one found user (ldapmyadmin and other ldap enabled services find more)
- If different usernames are entered in the username test field on the login tab all are claimed to be found
- The plugin only imports the first user it gets from ldap

**Server configuration**

**Operating system:**
Debian 8 Jessie x64

**Web server:**
Apache2 2.4.10-10+deb8u5

**Database:**
mariadb 10.0.27-0+deb8u1

**PHP version:**
PHP 5.6.27-0+deb8u1

**ownCloud version: (see ownCloud admin page)**
ownCloud 8.2.8 (production) 

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

**Signing status (ownCloud 9.0 and above):**


Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

List of activated apps:

If you have access to your command line run e.g.:
Enabled:
  - activity: 2.1.4
  - files: 1.2.1
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
  - user_ldap: 0.7.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - files_locking
  - user_external
  - user_webdavauth


The content of config/config.php:

{
    "system": {
        "instanceid": "oc9tak8ejkvp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "file.lab"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/file.lab",
        "dbtype": "mysql",
        "version": "8.2.8.2",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "ldapIgnoreNamingRules": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "dbtableprefix": "oc_"
    }
}


**Are you using external storage, if yes which one:** 
nfs mapped external storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 
LDAP


With access to your command line run e.g.:
+-------------------------------+---------------------------------------------------------------------------------+
| Configuration                 |                                                                                 |
+-------------------------------+---------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                               |
| hasPagedResultSupport         |                                                                                 |
| homeFolderNamingRule          |                                                                                 |
| lastJpegPhotoLookup           | 0                                                                               |
| ldapAgentName                 | cn=admin,dc=lab                                                                 |
| ldapAgentPassword             | ***                                                                             |
| ldapAttributesForGroupSearch  |                                                                                 |
| ldapAttributesForUserSearch   |                                                                                 |
| ldapBackupHost                |                                                                                 |
| ldapBackupPort                |                                                                                 |
| ldapBase                      | dc=lab                                                                          |
| ldapBaseGroups                | o=lablicate,o=employees,dc=lab                                                  |
| ldapBaseUsers                 | ou=people,o=employees,dc=lab                                                    |
| ldapCacheTTL                  | 600                                                                             |
| ldapConfigurationActive       | 1                                                                               |
| ldapEmailAttribute            | mail                                                                            |
| ldapExperiencedAdmin          | 1                                                                               |
| ldapExpertUUIDGroupAttr       | ou                                                                              |
| ldapExpertUUIDUserAttr        | uid                                                                             |
| ldapExpertUsernameAttr        | uid                                                                             |
| ldapGroupDisplayName          | ou                                                                              |
| ldapGroupFilter               | (&(|(objectclass=organizationalUnit)))                                          |
| ldapGroupFilterGroups         |                                                                                 |
| ldapGroupFilterMode           | 0                                                                               |
| ldapGroupFilterObjectclass    | groupOfNames                                                                    |
| ldapGroupMemberAssocAttr      | member                                                                          |
| ldapHost                      | ******                                                                   |
| ldapIgnoreNamingRules         |                                                                                 |
| ldapLoginFilter               | (&(objectclass=inetOrgPerson)(memberof=cn=nasusers,ou=groups,dc=lab)(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                 |
| ldapLoginFilterEmail          | 0                                                                               |
| ldapLoginFilterMode           | 0                                                                               |
| ldapLoginFilterUsername       | 1                                                                               |
| ldapNestedGroups              | 1                                                                               |
| ldapOverrideMainServer        |                                                                                 |
| ldapPagingSize                | 500                                                                             |
| ldapPort                      | 389                                                                             |
| ldapQuotaAttribute            |                                                                                 |
| ldapQuotaDefault              |                                                                                 |
| ldapTLS                       | 0                                                                               |
| ldapUserDisplayName           | displayname                                                                     |
| ldapUserDisplayName2          |                                                                                 |
| ldapUserFilter                | (&(objectclass=inetOrgPerson)(memberof=cn=nasusers,ou=groups,dc=lab))           |
| ldapUserFilterGroups          | nasusers                                                                        |
| ldapUserFilterMode            | 1                                                                               |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                   |
| ldapUuidGroupAttribute        | auto                                                                            |
| ldapUuidUserAttribute         | auto                                                                            |
| turnOffCertCheck              | 1                                                                               |
| useMemberOfToDetectMembership | 1                                                                               |
+-------------------------------+---------------------------------------------------------------------------------+

**Client configuration**

**Browser:**
Firefox Windows (newest)

**Operating system:**
Windows 8.1

**Logs**
**Web server error log**
none

Insert your webserver log here

**ownCloud log (data/owncloud.log)**

{"reqId":"eVIkJNWZGk159XOdCafs","remoteAddr":"","app":"user_ldap","message":"No DN found for  on ******","level":0,"time":"2016-11-18T10:33:46+00:00","method":"--","url":"--"}


Browser log

Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'.(unbekannt)
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Weitere Informationen]jquery.min.js:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src http://file.lab 'unsafe-eval'").admin
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src http://file.lab 'unsafe-eval'").admin:1
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.jquery.min.js:5:17117

**Comment by V1TA5** [comment]
Any advice?

**Comment by V1TA5** [comment]
This is till an Issue. Would be lovely if someone could give me any advice or find out if its a ug.

**Comment by butonic** [comment]
@V1TA5 please try again with OC10. It uses a completely rewritten ldap access code as well as a db account table. If it is still a problem please send us a full config report, as it contains the full LDAP config, which we neet to better understand your environment. 

Looking at the above ldap config the group base dn does not match your filters:

```
| ldapBaseGroups | o=lablicate,o=employees,dc=lab |
| ldapLoginFilter | (&(objectclass=inetOrgPerson)(memberof=cn=nasusers,ou=groups,dc=lab)(uid=%uid)) |
| ldapUserFilter | (&(objectclass=inetOrgPerson)(memberof=cn=nasusers,ou=groups,dc=lab)) |
```

the memberof group is not in your group base dn? closing, reopen with updated info if it still does not work with OC10
