### ISSUE TITLE
updating to 9.1.2 throws error "OC\ServerNotAvailableException: Connection to LDAP server could not be established"

### ISSUE THREAD

**Issue by awunder** [owncloud/user_ldap#28]
Hello all, i went through the upgrade from 8.1.3 and it went smoothly up until 9.0.6.. after that i went to 9.1.2 and during the occ upgrade it throws out that error:

OC\ServerNotAvailableException: Connection to LDAP server could not be established
Update failed
Maintenance mode is kept active
Reset log level

and i am back at the shell.. 
thats unfortunate as the server aint running anymore.. anyone of you guys have a hint on where to look at?

fwiw ldap server is running fine...

thanks a lot,
Andreas

**Comment by PVince81** [comment]
Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md
