### ISSUE TITLE
save button for ldap config

### ISSUE THREAD

**Issue by akurach** [owncloud/user_ldap#285]
Hello, pls add save config button to config settings page. 
Got a lot of problems with autofill in the browser.

**Comment by voroyam** [comment]
Thanks for the feedback. 

We are currently working on a new version of the config settings page.

**Comment by PVince81** [comment]
new version in the works here https://github.com/owncloud/user_ldap/pull/210

**Comment by VicDeo** [comment]
closing as a duplicate of https://github.com/owncloud/user_ldap/issues/27
