### ISSUE TITLE
[For 10.1] LDAP 0.13.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#305]
### Reason
- [x] set max version to 10 because core platform is switching to Semver: https://github.com/owncloud/user_ldap/pull/319
- [x] jump over invalid quota: https://github.com/owncloud/user_ldap/pull/237
- [x] resolve dn encoding issues: https://github.com/owncloud/user_ldap/pull/248

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Test: Install from the provided tarball and enable in ownCloud stable10 and check it works
- ❌  Test: Update Screenshot https://github.com/owncloud/user_ldap/pull/306

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml: https://github.com/owncloud/user_ldap/pull/323
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01): https://github.com/owncloud/user_ldap/pull/323
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://cloud.owncloud.com/index.php/s/TrvzazQLNfVzUXB
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/user_ldap/pull/325

**Comment by PVince81** [comment]
@davitol please test RC https://cloud.owncloud.com/index.php/s/TrvzazQLNfVzUXB

**Comment by davitol** [comment]
https://github.com/owncloud/user_ldap/pull/306#issuecomment-445783866

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready. 




> #306 (comment)

We should investigate if it is a problem with internal marketplace, but it seems not related to the tarball
