### ISSUE TITLE
Standardize CI infrastructure

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_ldap#316]
- [ ] implement owncloud/coding-standard in ``vendor-bin``
- [ ] move ``phpunit.xml`` to root folder
- [ ] use phpunit from core
- [ ] add ``test-acceptance-*`` to ``Makefile`` and use it from drone
- [ ] add ``test-php-unit`` to ``Makefile`` and use it from drone
- [ ] review the CI infrastructure and standardize anything else

Part of https://github.com/owncloud/QA/issues/582

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @individual-it.

A possibly related issue is https://github.com/owncloud/user_ldap/issues/273 (Move remaining CI from Travis to drone).

**Comment by skshetry** [comment]
Closing this as the PR is merged.
