### ISSUE TITLE
set low (2 sec) timeout for bind requests

### ISSUE THREAD

**Issue by butonic** [owncloud/user_ldap#320]
when a load balancer sporadically points to a non existing ldap server the ldap bind request might wait for a timeout. which might be foever on some of the requests, because we remove the php timeout to get long running tasks like file assembly done.

decreasing it to 2 sec should be good enough:

from http://blog.davidvassallo.me/2013/05/03/nugget-post-setting-ldap-connection-timeout-for-php/
```php
$ldapconn = ldap_connect(“192.168.1.1”);
ldap_set_option($ldapconn, LDAP_OPT_NETWORK_TIMEOUT, 2); /* 2 second timeout */
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @felixboehm.
