### ISSUE TITLE
Run all tests from core

### ISSUE THREAD

**Issue by skshetry** [owncloud/user_ldap#331]
Currently, we need to manually add to `behat.yml` config to run tests from the core. But, this might make our test suite run out of sync with the master.  So, we need to research some way to make all tests run from the core.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @individual-it.

Possibly related issues are https://github.com/owncloud/user_ldap/pull/302 (Add more tests to drone), https://github.com/owncloud/user_ldap/issues/274 (fix merge test), https://github.com/owncloud/user_ldap/issues/272 (run core api tests to be run in LDAP environment), https://github.com/owncloud/user_ldap/pull/308 (Adjust acceptance test step text similar to core), and https://github.com/owncloud/user_ldap/issues/66 (Fix test failures).

**Comment by individual-it** [comment]
This is difficult because we need the LDAPGEneralContext to import the preset LDIF file

**Comment by skshetry** [comment]
I believe this was completed on #354.

cc @individual-it @dpakach

**Comment by individual-it** [comment]
@skshetry I thought this issue is about how to make the tests in user_ldap run automatically also new suites of core. that did not happen yet and I have no idea how to achieve it

**Comment by individual-it** [comment]
@skshetry @phil-davis @paurakhsharma @dpakach any good ideas how we can accomplish to run all core tests in LDAP without having to rewrite the behat.yml in ldap repo?
If not then we should clone this issue

**Comment by individual-it** [comment]
closing this as there is no idea how to achieve the task. we need to remember to add new core suites also in ldap
