### ISSUE TITLE
Fix behat.yml to use new occ contexts

### ISSUE THREAD

**Issue by dpakach** [owncloud/user_ldap#339]
The occ context in acceptance tests was split into two more contexts in PR https://github.com/owncloud/core/pull/34131 . But this app still uses only occContext.
That needs to be fixed.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/user_ldap/pull/315 (fix paging when limit is used), https://github.com/owncloud/user_ldap/issues/35 (Use behat framework for acceptance tests), https://github.com/owncloud/user_ldap/issues/274 (fix merge test), and https://github.com/owncloud/user_ldap/issues/66 (Fix test failures).

**Comment by dpakach** [comment]
Fixed by #349
