### ISSUE TITLE
Add api and webUI acceptance tests for modifying ldap user's attributes

### ISSUE THREAD

**Issue by dpakach** [owncloud/user_ldap#343]
check what can/cannot happen with respect to modifying attributes of LDAP users
(clues in comment https://github.com/owncloud/core/pull/32731#issuecomment-428204236 )

- Similar Issue for occ - #292

- [x] provisioning API #346
- [x] using the webUI (might be more difficult to test - for core master the user_management app would need to be installed/enabled, for core stable10 the user_management app should already be there) #360

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/user_ldap/issues/292 (Add occ command acceptance tests), https://github.com/owncloud/user_ldap/issues/250 (load users and groups fully into acceptance tests), https://github.com/owncloud/user_ldap/pull/302 (Add more tests to drone), https://github.com/owncloud/user_ldap/issues/272 (run core api tests to be run in LDAP environment), and https://github.com/owncloud/user_ldap/issues/317 (Can't delete LDAP users).

**Comment by individual-it** [comment]
this is done, closing
