### ISSUE TITLE
adding a local user to an LDAP group fails but does not show an error

### ISSUE THREAD

**Issue by individual-it** [owncloud/user_ldap#345]
A local user cannot be member of a LDAP group, according to @butonic this is correct.
But when trying to do so neither UI nor API does return an error.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/user_ldap/issues/279 (Cannot add a comment containing an emoji when an LDAP user), https://github.com/owncloud/user_ldap/issues/205 (Transfer users local to users ldap), https://github.com/owncloud/user_ldap/issues/317 (Can't delete LDAP users), https://github.com/owncloud/user_ldap/issues/97 ([10.0.0] Show disable users -- ldap:check-user??), and https://github.com/owncloud/user_ldap/issues/102 (Unable to see ldap users).
