### ISSUE TITLE
Use behat framework for acceptance tests

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/user_ldap#35]
Currently integration tests are done using a personal approach, they are not using any test framework. In the current approach when a test fails, no more tests will run.

Having behat here would improve the readability of the tests and information after failures.

**Comment by davitol** [comment]
Checklist about what test needs to be covered

[ ] Test that a faulty host will does not connect successfully

[ ] Test that a connect succeeds when only a hostname is provided

[ ] Test that a connect succeeds when an LDAP URL is provided

[ ] Test that a connect succeeds when an LDAP URL with port is provided

[ ] Test that a connect succeeds when a hostname with port is provided

[ ] Test that a backup connection is being used when the main LDAP server is offline

[ ] Test that an exception is thrown if LDAP main server and LDAP backup server are not available

[ ] Test that an exception is thrown if main LDAP server is down and a backup server is not given

[ ] Test fetchUserByLoginName where it is expected that the login name does not match any LDAP user

[ ] Test fetchUserByLoginName where it is expected that the login name does match one LDAP user

[ ] Test countUsersByLoginName where it is expected that the login name does not match any LDAP user

[ ] Test countUsersByLoginName where it is expected that the login name does not match any LDAP user

[ ] Test countUsersByLoginName where it is expected that the login name does match one LDAP user

[ ] Test whether the group filter works with one specific group, while the input is the same.

[ ] Test whether a filter for limited groups is effective when more existing groups were passed for validation.

[ ] Test whether a filter for limited groups is effective when more existing groups were passed for validation.

[ ] Test that paging works properly against a simple example (reading all of few users in smallest steps)

**Comment by PVince81** [comment]
Thanks!

**Comment by PVince81** [comment]
- [ ] Create share to a LDAP group "ldap_group1", delete the group inside LDAP. The members of the group should not see the received share any more. (I saw that the share entry still exists in oc_share)

**Comment by PVince81** [comment]
-> triage

not sure about QA priorities for automated tests

**Comment by individual-it** [comment]
working on a set of acceptance tests. They will use a mix of UI and API tests (both now called "acceptance" in core). See https://github.com/owncloud/user_ldap/tree/master/tests/acceptance

**Comment by individual-it** [comment]
hijacking this thread to collect ideas about what need to be tested
CC @butonic @tomneedham @patrickjahns @phil-davis

**Comment by individual-it** [comment]
note to myself: backup servers can be configured in the advance tab. A second server is not a backup server
![image](https://user-images.githubusercontent.com/2425577/51314941-2bd11b00-1a79-11e9-80e6-95b302e9327c.png)

**Comment by phil-davis** [comment]
@individual-it can this long-running issue be closed?

**Comment by individual-it** [comment]
All done closing.
Please open new issues if you have more ideas for tests
