### ISSUE TITLE
make sure all core tests run on user_ldap

### ISSUE THREAD

**Issue by individual-it** [owncloud/user_ldap#354]
new suites in core need to be registered in user_ldap, so make sure all current suites run applicable tests also on user_ldap

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/user_ldap/issues/331 (Run all tests from core), https://github.com/owncloud/user_ldap/issues/150 (Test results for user_ldap release/0.10.0), https://github.com/owncloud/user_ldap/issues/353 (make federation server running a true own instance), https://github.com/owncloud/user_ldap/issues/272 (run core api tests to be run in LDAP environment), and https://github.com/owncloud/user_ldap/issues/348 (run acceptance tests with LDAPS).

**Comment by dpakach** [comment]
@phil-davis  I tried running those core test suites but all of those seem to fail in when running with `TEST_EXTERNAL_USER_BACKENDS=true` set.

**Comment by individual-it** [comment]
is this finished? closing?

**Comment by dpakach** [comment]
Requires #367 and #369

**Comment by dpakach** [comment]
Every core suite runs on user_leap now except `apiProvisioning-v1` and `apiProvisioning-v2`
