### ISSUE TITLE
Add quota related tests for LDAP users

### ISSUE THREAD

**Issue by dpakach** [owncloud/user_ldap#368]
#343 added tests for various user attributes for ldap users usning occ, API and webui.
But there are no tests for changing quota of a LDAP user.

 Add tests for checking what can/cannot happen with respect to modifying quota of LDAP users using
- [x] occ (quota cannot be set by occ command)
- [x] API
- [x] webUI

Consider the admin changing quota locally in ownCloud, then sync the user and check that the local "override" of quota is still in effect. LDAP should always have authority. see https://github.com/owncloud/core/pull/32731#issuecomment-428204236
> this means that if LDAP is enabled we should prevent any modification of fields email, avatar, display name or quota if an LDAP attribute is specified for such fields in the config. If no field is specified, allow the admin to set values in the users page.

if we agree on this we can raise a new ticket to make the necessary changes for blocking input for all these fields in the users page, provisioning API and occ commands.

Work out how to "reset" the local override so that the quota from LDAP is used again - test that.

**Comment by phil-davis** [comment]
See https://github.com/owncloud/core/pull/34467 for a proposed core change that should make this "quota overriding" work.

**Comment by PVince81** [comment]
- [ ] also test quota overrides: https://github.com/owncloud/core/pull/34467

**Comment by individual-it** [comment]
quota overrides tested in #412
