### ISSUE TITLE
Acceptance test fails for user who is excluded from sharing tries to share a file with another user

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_ldap#378]
These new core test scenarios are failing with LDAP:
```
--- Failed scenarios:

    /var/www/owncloud/server/tests/acceptance/features/apiShareManagement/createShare.feature:397
    /var/www/owncloud/server/tests/acceptance/features/apiShareManagement/createShare.feature:399
    /var/www/owncloud/server/tests/acceptance/features/apiShareManagement/createShare.feature:439
    /var/www/owncloud/server/tests/acceptance/features/apiShareManagement/createShare.feature:441

182 scenarios (178 passed, 4 failed)
2115 steps (2111 passed, 4 failed)
```
The user doing the sharing is in a group that is excluded from sharing, but still is able to share a file or folder.

Needs investigation.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/user_ldap/issues/250 (load users and groups fully into acceptance tests), https://github.com/owncloud/user_ldap/issues/348 (run acceptance tests with LDAPS), https://github.com/owncloud/user_ldap/issues/350 (test "sharing with non unique group name" always fails the first time), https://github.com/owncloud/user_ldap/issues/343 (Add api and webUI acceptance tests for modifying ldap user's attributes), and https://github.com/owncloud/user_ldap/issues/364 (local user tries to access item shared by a LDAP user when LDAP server is offline).

**Comment by phil-davis** [comment]
Looks to be related to acceptance test code issues that also cause https://github.com/owncloud/core/issues/33733
Could be fixed by core PR https://github.com/owncloud/core/pull/35551

**Comment by phil-davis** [comment]
@haribhandari07 please check if the tests mentioned here are still failing.
Hopefully tonight we will get a clean run of user_ldap CI.

**Comment by phil-davis** [comment]
Note: `createShare.feature` is in suite `apiShareManagementBasic` these days.

**Comment by phil-davis** [comment]
The scenarios were unskipped by core PR https://github.com/owncloud/core/pull/35559 https://github.com/owncloud/core/pull/35551
All is good.
