### ISSUE TITLE
Add apiAuth acceptance test suite

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_ldap#380]
https://github.com/owncloud/core/pull/34643 added a new core acceptance test suite `apiAuth`

Also add it to user_ldap drone.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/user_ldap/pull/302 (Add more tests to drone), https://github.com/owncloud/user_ldap/issues/343 (Add api and webUI acceptance tests for modifying ldap user's attributes), https://github.com/owncloud/user_ldap/pull/311 (Adjust acceptance test steps changed in core), https://github.com/owncloud/user_ldap/pull/308 (Adjust acceptance test step text similar to core), and https://github.com/owncloud/user_ldap/issues/368 (Add quota related tests for LDAP users).

**Comment by phil-davis** [comment]
Note: needs to be done tomorrow after the nightly core QA tarballs are built. At that time the new acceptance test suite will "really exist" in core.

**Comment by phil-davis** [comment]
PR #381 is awaiting the next core QA tarballs, should pass CI tomorrow morning.

**Comment by phil-davis** [comment]
PR merged
