### ISSUE TITLE
Unable to search user by  displayName

### ISSUE THREAD

**Issue by goodkiller** [owncloud/user_ldap#43]
I have problem to search users by displayName for file sharing.

PHP 7.0, Nginx/1.11.7

### OpenLDAP object
cn=3920,cn=users,dc=xx,dc=yy
displayName = Simple User
uid = 3920

### user_ldap configuration

        "user_ldap": {
            "enabled": "yes",
            "types": "authentication",
            "ldap_host": "ldap.xx.yy",
            "ldap_backup_host": "",
            "ldap_backup_port": "",
            "ldap_turn_off_cert_check": "0",
            "ldap_userfilter_groups": "",
            "ldap_tls": "0",
            "ldap_groupfilter_objectclass": "posixGroup",
            "ldap_base_users": "cn=users,dc=xx,dc=yy",
            "ldap_groupfilter_groups": "",
            "ldap_email_attr": "mail",
            "ldap_base_groups": "ou=organizations,cn=production,dc=xx,dc=yy",
            "home_folder_naming_rule": "",
            "last_jpegPhoto_lookup": "0",
            "ldap_paging_size": "500",
            "ldap_port": "389",
            "ldap_agent_password": "xxxxxxxx",
            "ldap_dn": "cn=admin,dc=xx,dc=yy",
            "ldap_quota_attr": "ownCloudQuota",
            "ldap_configuration_active": "1",
            "ldap_override_main_server": "0",
            "ldap_group_display_name": "cn",
            "ldap_group_filter_mode": "0",
            "ldap_userlist_filter": "(&(|(objectclass=inetOrgPerson)))",
            "ldap_group_member_assoc_attribute": "memberUid",
            "ldap_cache_ttl": "600",
            "ldap_group_filter": "(&(|(objectclass=posixGroup)))",
            "has_memberof_filter_support": "1",
            "ldap_login_filter_mode": "1",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_attributes": "mail",
            "ldap_loginfilter_username": "1",
            "ldap_userfilter_objectclass": "inetOrgPerson",
            "ldap_nested_groups": "1",
            "ldap_base": "dc=xx,dc=yy",
            "ldap_experienced_admin": "0",
            "ldap_attributes_for_group_search": "",
            "use_memberof_to_detect_membership": "0",
            "ldap_expert_uuid_group_attr": "gidNumber",
            "ldap_quota_def": "1GB",
            "ldap_expert_username_attr": "uid",
            "ldap_expert_uuid_user_attr": "uid",
            "installed_version": "0.9.0",
            "cleanUpJobOffset": "9850",
            "enforce_home_folder_naming_rule": "",
            "ldap_user_display_name_2": "",
            "ldap_dynamic_group_member_url": "",
            "ldap_login_filter": "(&(&(|(objectclass=inetOrgPerson)))(|(uid=%uid)(|(mail=%uid))))",
            "ldap_attributes_for_user_search": "",
            "ldap_user_filter_mode": "1",
            "ldap_display_name": "displayName"
        }

### Table public.oc_ldap_user_mapping content
'cn=3920,cn=users,dc=xx,dc=yy';'3920';'3920'
'cn=3550,cn=users,dc=xx,dc=yy';'3550';'3550'
'cn=3561,cn=users,dc=xx,dc=yy';'3561';'3561'
'cn=3580,cn=users,dc=xx,dc=yy';'3580';'3580'
...
Total rows: 4043

**Search results by searching uid (3920):**
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":null},"data":{"exact":{"users":[{"label":Simple User","value":{"shareType":0,"shareWith":"3920"}}],"groups":[],"remotes":[]},"users":[],"groups"
:[],"remotes":[]}}}

Search results by searching displayName (Simple):
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":null},"data":{"exact":{"users":[],"groups":
[],"remotes":[]},"users":[],"groups":[],"remotes":[]}}}

Please also notice that all share searches are extremely slow. I also using memcached and APCu. Searching takes about 2 minutes or Nginx timeout.

Can anyone help me about this slowness and why I can not search users by name.

**Comment by goodkiller** [comment]
Anyone :) ?

**Comment by goodkiller** [comment]
UP!

**Comment by butonic** [comment]
`"ldap_attributes_for_user_search": "",` if no attribute is given it will use uid I think. What does
```
occ ldap:show-config | grep ldapAttributesForUserSearch
```
give.

In the ldap config find "advanced configuration" -> "Directory Settings" -> "User Search Attributes" and add displayname. Probably also email. Also consider a 2nd User Display Name filed to distinguish users with the same display name.

See https://doc.owncloud.org/server/latest/admin_manual/configuration_user/user_auth_ldap.html?highlight=ldap#directory-settings for more information.

Reopen if you still have problems. Post the full output of `occ ldap:show-config` and run oc in debug mode to paste the log that is written during a user search.
