### ISSUE TITLE
LDAP cache init race condition

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#45]
When the cache (memcache) is empty, if multiple PHP requests trigger for example `countUsersInGroup` at the same time, they will all connect to the LDAP server to retrieve that information and all will also store the same information at the end of the process, each overwriting each other and the slowest one will win.

It gets worse if during this process, some information changes on the LDAP server and the winning process is not the one that got the most recent information.

In any case, this shouldn't cause any big issues because the values have a TTL and will be refreshed eventually. The biggest issue I think is only that there will be an initial peak load when the server gets hammered (sync clients?) while the cache is cold.

Maybe looking deeper at all the cache code paths might reveal some real potential issues that could come out of it. (this, excluding the other known issue of cache inconsistency https://github.com/owncloud/user_ldap/issues/30).

So one idea here would be to add additional memcache keys to lock entries while they are being computed. Or, after the computation is done, the cached value needs to first be reread to see if it matches what we had before. Or check its update / TTL value as validation.

On the other hand, if we introduce a user account table https://github.com/owncloud/core/issues/23558 this problem might become obsolete, because in the latter case there would be a single background process to update all values, which means no concurrency.

@DeepDiver1975 @jvillafanez @butonic @IljaN

**Comment by butonic** [comment]
ldap access completely rewritten and the caching behavior fixed with https://github.com/owncloud/user_ldap/pull/125

also account table makes a lot of ldap user count cases obsolete. now only needed for user sync
