### ISSUE TITLE
Cannot log into ownCloud Server when one of the LDAP Servers are not available

### ISSUE THREAD

**Issue by davitol** [owncloud/user_ldap#48]
### Steps to reproduce
1. As admin enable LDAP app
2. In LDAP section enable two LDAP configurations
3. Make one of the LDAP server backend not accesible (in my scenario, the LDAP server container was paused)
4. Try to log in with a user from the other LDAP Server

### Expected behaviour

The users that belongs to the other LDAP server should be able to log in

### Actual behaviour

No user can log into the oC server.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**ownCloud version:**

"9.1.3.1","versionstring":"9.1.3","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
No logs related this issue
```

### Client configuration

**browser**

 Mozilla

@jvillafanez

**Comment by PVince81** [comment]
hesitating between medium and high...

@cdamken FYI

**Comment by jvillafanez** [comment]
I'll need information about the expectation for the rest of users, the ones belonging to the LDAP server which is down. They'll probably be missing and we might need to deal with ghost users (for sharing and maybe other areas).

**Comment by PVince81** [comment]
Ideal would be that we have the user account table (@DeepDiver1975 https://github.com/owncloud/core/issues/23558) and we don't need to do anything. In the user account table concept ideas, there would be a bkg job syncing the users from LDAP so if one LDAP is done it would only skip it.

Now if we don't have user account table, then one way would be to consider these users temporarily disabled. So trying to login as these users would give 503 and accessing their shares would also give 503 StorageNotAvailableException. I suggest we wait for #23558 before thinking of any solution.

**Comment by PVince81** [comment]
We might want to think of a backportable quickfix though.

**Comment by jvillafanez** [comment]
https://github.com/owncloud/user_ldap/issues/50 as potential fix

**Comment by jvillafanez** [comment]
I'll need expectations here. Are we going to keep considering LDAP as a critical resource and explode if it isn't available for one of the servers? Any other options to consider?
Note that we might need group information that might not be available because the LDAP server coudl be down.

**Comment by butonic** [comment]
cannot reproduce with current master / release branch please open a new issue because the code has undergone heavy changes
