### ISSUE TITLE
LDAP 0.15.0

### ISSUE THREAD

**Issue by micbar** [owncloud/user_ldap#481]
### Reason

- Release needed for https://github.com/owncloud/user_ldap/pull/470

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "0.15.0 Testplan" https://github.com/owncloud/user_ldap/issues/482 @davitol 

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) =>https://github.com/owncloud/user_ldap/issues/482 @davitol
#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [ ] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [ ] Smoke test tarball (at least install + enable)

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by micbar** [comment]
@davitol we have https://github.com/owncloud/user_ldap/releases/tag/v0.15.0RC1

**Comment by micbar** [comment]
@davitol We also created a Testplan because we were trying if the handbook / Checklists work.

**Comment by davitol** [comment]
> @davitol we have https://github.com/owncloud/user_ldap/releases/tag/v0.15.0RC1

Tarball is QA-ready. We need a final tarball @jnweiger @micbar

**Comment by pmaier1** [comment]
Close?

**Comment by davitol** [comment]
> Close?

Released last Dec. 20th and already in marketplace so I guess we should close it, yes.
