### ISSUE TITLE
Clicking settings button leads to error

### ISSUE THREAD

**Issue by AdminValida** [owncloud/user_ldap#484]
Hi!

We are using ownCloud 10.3.1 on Ubuntu 18.04.3 LTS and Apache 2.4.29. We are able to login with our LDAP accounts but clicking on the settings button produces the following error:

![image](https://user-images.githubusercontent.com/23398578/70222210-fb09db00-1749-11ea-9ea2-fe4d98f717b3.png)
![image](https://user-images.githubusercontent.com/23398578/70222254-0bba5100-174a-11ea-9e71-22cacadcdff7.png)

```
Dec  5 09:52:54 HOSTNAME ownCloud[13271]: [JE5FttI4uTGhBEru5Jda][IP][89591EE5-532F-4A06-BBDE-E0762256B3DE][index][GET][/owncloud/settings/personal] Exception: {"Exception":"OCA\User_LDAP\Exceptions\DoesNotExistOnLDAPException","Message":"89591EE5-532F-4A06-BBDE-E0762256B3DE","Code":0,"Trace":"
#0 /var/www/owncloud/lib/private/User/User.php(361): OCA\User_LDAP\User_Proxy->canChangeAvatar('89591EE5-532F-4...')
#1 /var/www/owncloud/settings/Panels/Personal/Profile.php(101): OC\User\User->canChangeAvatar()
#2 /var/www/owncloud/settings/Controller/SettingsPageController.php(167): OC\Settings\Panels\Personal\Profile->getPanel()
#3 /var/www/owncloud/settings/Controller/SettingsPageController.php(85): OC\Settings\Controller\SettingsPageController->getPanelsData(Array)
#4 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(153): OC\Settings\Controller\SettingsPageController->getPersonal('general')
#5 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(85): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\SettingsPageController), 'getPersonal')
#6 /var/www/owncloud/lib/private/AppFramework/App.php(100): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\SettingsPageController), 'getPersonal')
#7 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('SettingsPageCon...', 'getPersonal', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#8 /var/www/owncloud/lib/private/Route/Router.php(342): OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#9 /var/www/owncloud/lib/base.php(920): OC\Route\Router->match('/settings/perso...')
#10 /var/www/owncloud/index.php(54): OC::handleRequest()
#11 {main}","File":"/var/www/owncloud/apps/user_ldap/lib/User_Proxy.php","Line":244}
```

This error does not occur if i use an internal user.

If i comment the line 244 in "*\owncloud\apps\user_ldap\lib\User_Proxy.php" the error does not occur and i am able to enter "settings".

Maybe that's a problem with our ldap, can anyone point me to the right direction?

Regards

**Comment by handswork** [comment]
I do have the same issue. not fixed in 10.3.2.2, with the latest 0.14.0 LDAP Integration

**Comment by handswork** [comment]
Still not fixed in 0.15.0

**Comment by N4v41** [comment]
still not fixed in 0.15.1

**Comment by AdminValida** [comment]
Seems to be fixed, we are using 10.5.0 right now.

Regards

**Comment by cdamken** [comment]
@IljaN Can you take care?

**Comment by cdamken** [comment]
the problem looks still in oC10.7 and user_ldap 0.15.2



We tried:

1. disabling the avatars in `config.php`
2. disabling the theme
3. removing the avatars folder

None of those workarounds worked.

The only working workaround so far:

> If I comment the line 244 in "*\owncloud\apps\user_ldap\lib\User_Proxy.php" the error does not occur and I am able to enter "settings".

**Comment by darootler** [comment]
Interesting, the problem is gone in our environment. Maybe this has something to do with orphaned ldap users?

Regards
Richard
