### ISSUE TITLE
LdapEnforceChannelBinding

### ISSUE THREAD

**Issue by RodNoc42** [owncloud/user_ldap#491]
Microsoft will reject all unsigned LDAP-Requests with the Windows Update in March 2020 to prevent Man-in-the-middle-attacks.
Our AD-Administrator turned loggin on and we can see in the eventlog, that the owncloud-server will be rejected in the future.
Here are more information from microsoft.
https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV190023

There is a good summary (but only in german) for this here:
https://www.msxfaq.de/windows/sicherheit/ldapenforcechannelbinding.htm

**Comment by micbar** [comment]
@enbrnz Unassigning myself.
This needs to go to the product board.

**Comment by micbar** [comment]
Carlos already moved the EE ticket.
Closing here, duplicate.

**Comment by mr-flibble** [comment]
What is status with this? And with what issue is this duplicate ?
