### ISSUE TITLE
Adjust settings page section

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#52]
With the new settings page in 10.0, the LDAP settings appear under "Additional settings" which is not easy to find at all for admins.

The app needs to be adjusted to use the new interfaces (@tomneedham can you point to the matching developer documentation ?) in order to have a "LDAP" section in the left sidebar.

Setting this to high because I'm pretty sure admins will be very confused and frustrated.

**Comment by PVince81** [comment]
bug as in "UX bug"

**Comment by PVince81** [comment]
Too bad we don't have subsections, else we could in the future put the tabs of the wizard into several subsections

**Comment by DeepDiver1975** [comment]
Question: do we need the wizard in 10?

**Comment by PVince81** [comment]
We still need a way to configure the LDAP connection and various filters to know what and how to import stuff into the account table.

**Comment by DeepDiver1975** [comment]
yes - most probably ... we will see

**Comment by PVince81** [comment]
@tomneedham can you first prepare developer docs ? Then maybe other people would be able to help adjusting this. (for example @noveens)
