### ISSUE TITLE
How Quota Default field of LDAP wizard works?

### ISSUE THREAD

**Issue by davitol** [owncloud/user_ldap#55]
The admin manual says:

```
Quota Default:

    Override ownCloud default quota for LDAP users who do not have a quota set in the Quota Field.

        Example: 15 GB
```

But IMHO this field does not work in any way. I have tried several values and configurations and it did not work.

![screen shot 2017-02-17 at 10 12 00](https://cloud.githubusercontent.com/assets/10596560/23059435/b3424534-f4f9-11e6-8539-b0fe3180abab.png)

![screen shot 2017-02-17 at 10 16 53](https://cloud.githubusercontent.com/assets/10596560/23059551/3aa8212e-f4fa-11e6-86e0-c8cf553a9909.png)

**Comment by PVince81** [comment]
Default inconsistencies was fixed recently.
Also see https://github.com/owncloud/documentation/issues/2885
