### ISSUE TITLE
user_ldap 0.15.2

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/user_ldap#577]
### Reason

- Release needed for https://github.com/owncloud/user_ldap/pull/551

### Product approval

- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Create release branch with the format "release-$version"
- [x] Create "0.15.2" TestPlan @davitol 

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in the ticket => @davitol
#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol @cdamken RC1 available at https://github.com/owncloud/user_ldap/releases/tag/v0.15.2RC1

**Comment by davitol** [comment]
- Sanity tested and LGTM. Tested with oC10.4.1 and PHP 7.1 and oC 10.5 and PHP 7.4 using OpenLDAP.

**Comment by HanaGemela** [comment]
Currently being tested by a customer. @cdamken let us know if it passed testing

**Comment by cdamken** [comment]
The customer(s) sadly haven't answered, I provided to  4 who had some different issues that should be fixed already and are not possible to reproduce in our own test environments.

IMHO if they don't have feedback until Monday and you haven't found any additional bugs we could release it and the next step will be testing with the 10.5 and the 0.15.2. Agree?

**Comment by jnweiger** [comment]
okay, fine with me. The "next step" is already done. @davitol already succeeded a sanity test with oC 10.5 and PHP 7.4 using OpenLDAP -- let's move ahead!

**Comment by NannaBarz** [comment]
Is there a release date for ldap-0.15.2? A customer is asking

**Comment by jnweiger** [comment]
marketplace release done!
