### ISSUE TITLE
drone CI osixia/openldap failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_ldap#578]
e.g. https://drone.owncloud.com/owncloud/user_ldap/2602/21/3
```
*** Running /container/run/process/slapd/run...
5ee838b8 @(#) $OpenLDAP: slapd 2.4.50+dfsg-1~bpo10+1 (May  4 2020 05:25:06) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5ee838b8 slapd starting
5ee838b8 daemon: listen(ldap://e0055167c175:389, 5) failed errno=98 (Address already in use)
5ee838b8 slapd stopped.
*** /container/run/process/slapd/run exited with status 0
*** Killing all processes...
```
It gets `Address already in use` and exits. So then there is no LDAP server available.

https://drone.owncloud.com/owncloud/user_ldap/2602/28/9
```
php occ ldap:test-config "LDAPTestId"

In Connection.php line 532:
                                                  
  [OCA\User_LDAP\Exceptions\BindFailedException] 
```
ownCloud cannot connect to an LDAP server, and the tests fail.

Note: https://github.com/osixia/docker-openldap/releases/tag/v1.4.0 - there was a new release 1.4.0  yesterday. I guess that has a problem (or some new environment variables need to be defined, or some other change to the setup)?

The docker images are at https://hub.docker.com/r/osixia/openldap/tags

If it is not easy to fix, we could for now pin to `1.3.0`. But it would be nice to fix it and run `1.4.0`

**Comment by phil-davis** [comment]
Note: similar problem in phoenix tests https://drone.owncloud.com/owncloud/phoenix/10039/35/17

**Comment by phil-davis** [comment]
Step 1: pin everything to `1.3.0` - see the linked PRs above.

**Comment by phil-davis** [comment]
If the 4 PRs above pass, then this issue is fixed.

**Comment by kiranparajuli589** [comment]
With PRs:
- https://github.com/owncloud/phoenix/pull/3741
- https://github.com/owncloud/phoenix/pull/3738
OpenLDAP is now up-pinned to the latest, (fixed for phoenix tests)

Other repositories `core`, `ocis`, `ocis-reva`, 'user_ldap` also have the latest OpenLSAP service running inside the respective drone runs.
So, closing!
