### ISSUE TITLE
Big HELP for everyone

### ISSUE THREAD

**Issue by patrikx3** [owncloud/user_ldap#59]
It took me 2 days to fix it up and all was good!

I think always add in the DOC to make sure Apache/FPM or any PHP program to use this environment:
**LDAPTLS_REQCERT=never**

It will work quickly!

**Comment by PVince81** [comment]
@settermjd @jvillafanez

**Comment by VicDeo** [comment]
I guess this is valid  in case there is a self-signed SSL certificate in chain and connection is performed via ldaps

**Comment by jvillafanez** [comment]
I agree with @VicDeo . We shouldn't do anything by ourselves.
It's the admin's responsability to setup an LDAP with or without TLS support. It's also the admin's responsability to properly configure TLS support (if the admin wants TLS) on both sides so they can communicate between themselves.

If you think there is a bug in the code, which might be, fill the issue template providing as much information as possible so we can have a look about what's happening. So far this seems a misconfiguration on your side.
