### ISSUE TITLE
Sonarcloud instead of codecov

### ISSUE THREAD

**Issue by mmattel** [owncloud/user_ldap#604]
codecov has been replaced by SonarCloud, but the setup has not been implemented in this repro so far.
codecov statuses are no longer "required" but triggered.
Someone should change the repo settings to reflect this.

Refs: https://github.com/owncloud/user_ldap/pull/599#issuecomment-740484676

@micbar 
@phil-davis

**Comment by phil-davis** [comment]
This applies to many of the oC10 app repos. I have given a list to @micbar 
I do not have enough admin privs on these repos to change the "required" CI statuses.

**Comment by phil-davis** [comment]
codecov is no longer required, and SonarCloud analysis is happening: https://sonarcloud.io/dashboard?id=owncloud_user_ldap
