### ISSUE TITLE
Run occ command   Group without search

### ISSUE THREAD

**Issue by jnweiger** [owncloud/user_ldap#641]
occ ldap:search --group requires a paramater.

Did it list all groups in earlier versions when caled without a group name?

**Comment by jnweiger** [comment]
Correct syntax is `occ ldap:search --group ''` -- the empty string is mandatory. :see_no_evil:

**Comment by mmattel** [comment]
@jnweiger is this docs relevant?

**Comment by jnweiger** [comment]
> @jnweiger is this docs relevant?

As far as I could see, `occ ldap:...`  commands are not explained in https://doc.owncloud.com/server/next/admin_manual/configuration/user/user_auth_ldap.html -- so nothing to do there, (or very much to do there...)
Maybe elsewhere.
