### ISSUE TITLE
[QA] info.svg icon missing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/user_ldap#642]
Seen in user_ldap 0.15.3-rc1 with core 10.8.0-beta1

Several messages start white rectangles. (e.g. where the mousepointer is).
The slightly bigger ones are checkboxes, the smaller ones are non-clickable.
![image](https://user-images.githubusercontent.com/1108546/124018059-bdce0380-d9e7-11eb-86f0-d9d52a964fd3.png)

Expected behaviour: 
* Some nicer info icons should be shown instead of the small rectangles.
* Compare "after" screenhots in https://github.com/owncloud/user_ldap/pull/597

**Comment by jnweiger** [comment]
My test instance is installed in /owncloud/
The icon would work, if accessed as /owncloud/core/img/actions/info.svg

**Comment by jnweiger** [comment]
Building RC2 with https://github.com/owncloud/user_ldap/commit/2781b9ed4dace9e626869667dc987815a5877c30, ...

**Comment by jnweiger** [comment]
Improvement in RC2, the broken image icon does not appear any more.
With a server under /owncloud/ we see whitespace, where the `i` should be.

![image](https://user-images.githubusercontent.com/1108546/124127900-8c534780-da7c-11eb-84eb-1f53fa10943d.png)

**Comment by jnweiger** [comment]
Workaround in /etc/apache2/sites-enabled/owncloud.conf:
```
Alias /owncloud "/var/www/owncloud/"
Alias /core/img/actions/info.svg "/var/www/owncloud/core/img/actions/info.svg"
```

With a test system running in `/` the workaround is not needed.

**Comment by jnweiger** [comment]
Not perfect, but Okayish.

**Comment by hurradieweltgehtunter** [comment]
Please check out branch `release-0.5.13` if it got fixed
