### ISSUE TITLE
[QA] Drop reference to ownCloud 5

### ISSUE THREAD

**Issue by jnweiger** [owncloud/user_ldap#643]
Seen in user_ldap 0.15.3-rc1 with core 10.8.0-beta1

![image](https://user-images.githubusercontent.com/1108546/124023532-52d3fb00-d9ee-11eb-9416-5c5fb248928a.png)

Expected behaviour: Do not discuss compatibility with unsupported historic versions

**Comment by jnweiger** [comment]
Further action items seen while testing:
* [ ] https://doc.owncloud.com/server/admin_manual/configuration/user/user_auth_ldap.html#user-and-group-mapping
refers to php 5.6

**Comment by mmattel** [comment]
@jnweiger imho this can be closed. Translations need to be done in transifex.

**Comment by jnweiger** [comment]
Confirmed fixed in 0.15.4-rc2
