### ISSUE TITLE
[QA] "Saving" confirmation goes outside of window

### ISSUE THREAD

**Issue by jnweiger** [owncloud/user_ldap#644]
Seen in user_ldap 0.15.3-rc1 with core 10.8.0-beta1

When the user tries to change entries, there is often no indicatio if the intended change was actually performed in the system.
There is a yellowish "Saving" message that pops up very briefly near the Continue button which is far away from the locus of attention. 
In the screenshot, the window was just tall enough. It can easily be scrolled off screen, as vertical space isn't cheap these days.

![image](https://user-images.githubusercontent.com/1108546/124024340-5caa2e00-d9ef-11eb-9edd-87599b85bb0f.png)

Expected behaviour:
 * Make the yellow message pop up in the usual place on the top where the logo is. (Also, I prefer yellow on blue over yellow on white)
 * (I remember the good old days, when we had Save buttons, that would put me in control)

**Comment by jnweiger** [comment]
The saving indicator does not appear at all for the Expert and Advanced tabs. 
This together with the red exclamation mark raises doubt ...

**Comment by hurradieweltgehtunter** [comment]
https://user-images.githubusercontent.com/16665512/124113122-5ce80f00-da6b-11eb-928b-78b0c3985276.mov

Moved the saving indicator into the tab bar to make it visible all time

**Comment by jnweiger** [comment]
Confirmed fixed in 0.15.3 RC2

![image](https://user-images.githubusercontent.com/1108546/124126562-17334280-da7b-11eb-819a-a88d304b850d.png)
