### ISSUE TITLE
[QA] name of the server configuration is only shown on the first tab

### ISSUE THREAD

**Issue by jnweiger** [owncloud/user_ldap#645]
Seen in user_ldap 0.15.3-rc1 with core 10.8.0-beta1

The first tab of the LDAP configuration wizard allows the creation of multiple configurations.
When changing settings, it is important to know which configuration is currently being worked on.
The name is prominently shown inside the first tab,
![image](https://user-images.githubusercontent.com/1108546/124027674-6fbefd00-d9f3-11eb-9287-51e2c4af711a.png)

But when working on the other tabs, there is no visual indication, which configuration they work on.
E.g. a configuration can be switched inactive in the Advanced tab, but there is no indication, which one.

![image](https://user-images.githubusercontent.com/1108546/124027971-c2001e00-d9f3-11eb-909c-24243db2e9bf.png)

Expected behaviour: all tabs show the name of the configuration that is being changed.

I'd suggest to e.g. use the area where we say "Configuration OK" to say "Configuration OK (server 2: xxxx.x..xxx.xx)"

**Comment by jnweiger** [comment]
PS: is it intended that Advanced and Expert tabs show the red warning exclamation mark, when apparently all is okay there?

**Comment by hurradieweltgehtunter** [comment]
![grafik](https://user-images.githubusercontent.com/16665512/124108651-a41fd100-da66-11eb-84d1-64f1a0f4a02f.png)

ok like this? Gets filled when changing tabs away from the "server" tab

**Comment by hurradieweltgehtunter** [comment]
> PS: is it intended that Advanced and Expert tabs show the red warning exclamation mark, when apparently all is okay there?

It is intended because of the sensitive settings here

**Comment by jnweiger** [comment]
Confirmed fixed in 0.15.3 RC3

![image](https://user-images.githubusercontent.com/1108546/124126724-41850000-da7b-11eb-8f38-86f98b7c3c96.png)
