### ISSUE TITLE
[QA] Login Attributes: LDAP Filter misagligned output

### ISSUE THREAD

**Issue by mmattel** [owncloud/user_ldap#653]
As you can see in the screenshots, only the Login Attributes tab (2.nd screenshot) has a misaligned LDAP filter output. The text "LDAP Filter" is on the right and not above. This should be corrected for the new release.

![image](https://user-images.githubusercontent.com/3321281/124628253-92806400-de80-11eb-901e-844ce6ff9885.png)

![image](https://user-images.githubusercontent.com/3321281/124628205-8a282900-de80-11eb-8fa2-4d659f516ccc.png)

![image](https://user-images.githubusercontent.com/3321281/124628139-7b417680-de80-11eb-9fff-77f9fea7ad40.png)

**Comment by mmattel** [comment]
@hurradieweltgehtunter or @JanAckermann mind to take a look if you could fix this?

**Comment by mmattel** [comment]
@hurradieweltgehtunter thanks a lot

**Comment by hurradieweltgehtunter** [comment]
happy to help :)

**Comment by mmattel** [comment]
@hurradieweltgehtunter has the commit be merged? I cant find it or I am just blind...

**Comment by hurradieweltgehtunter** [comment]
https://github.com/owncloud/user_ldap/commit/ce5e3a2ac3f8b6ed871982bdc9bfe3761418678b
