### ISSUE TITLE
[QA] Transifex is triggered manually instead automated

### ISSUE THREAD

**Issue by mmattel** [owncloud/user_ldap#657]
After a discussion with @ChrisEdS it turned out, that the user_ldap repo is not synced automatically with transifex. This should be changed immediately as changed strings are available on ownCloud to be uploaded/translated/downloaded for this repo.

@JanAckermann I was told that you are in charge fixing this 

@jnweiger fyi, pls add to #605

**Comment by JanAckermann** [comment]
@mmattel on which observation do you guess it is not working ?

If we have a look here, it should work https://drone.owncloud.com/owncloud/translation-sync/2016/33/12

**Comment by ChrisEdS** [comment]
I looked into the commit history, last sync run was on Jun 13, 2021. This is why I thought you have to trigger manually. Under what circumstances is a commit set? Every night when a change is made?

**Comment by JanAckermann** [comment]
@mmattel @ChrisEdS 
The runner fires every night a commit is set if there are newly translated strings in transifex and not yet committed to master, AFAIR only languages which are at least 70%(or so) translated will be taken.
On the other hand only strings which are in master, will get pushed to transifex

**Comment by JanAckermann** [comment]
I think the observation is, that this string is not in transifex correct?
https://github.com/owncloud/user_ldap/commit/9e8ac070e188d569bcb394fc7f989a04c21cfa4d

**Comment by JanAckermann** [comment]
https://github.com/owncloud/user_ldap/pull/654

The PR with the text change was merged 6 hours ago into master, our translation night runner was doing its job 8 ours ago, so you simply missed the train.

I suspect everything is running correctly.
(I uploaded the new string to transifex)

**Comment by mmattel** [comment]
@JanAckermann We have updated the transifex translation with the changes mentioned above from EN to DE. Mind to pull the changes from transifex so it can be shown within the next build?

@jnweiger fyi

**Comment by JanAckermann** [comment]
@mmattel Usually I don't want to interfere the standardized processes, If @micbar says it is okay, I can manually pull the translations....
