### ISSUE TITLE
[QA] Frontend breaks with other auser auth apps

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/user_ldap#659]
oauth2 + user_ldap breaks tabs view

**Comment by jnweiger** [comment]
![image](https://user-images.githubusercontent.com/1108546/124778390-3df0ed80-df41-11eb-885e-a239111bcbfc.png)

**Comment by jnweiger** [comment]
Confirmed fixed in 0.15.4-rc1: First oauth2, then user_ldap. No overlap.
