### ISSUE TITLE
Fix test failures

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#66]
https://travis-ci.org/owncloud/user_ldap/jobs/216974014

@jvillafanez can you have a look ?
Also make sure to check if the stable branches are affected.

cc @owncloud/qa

**Comment by jvillafanez** [comment]
Looks like core master is causing this. The LDAP code is working fine in core's commit "4b2d1d7599b9b0f41e6c89a8219c7c727a6bb513" (March 21th, around the time LDAP test started to fail). In addition, there hasn't been any code change that should cause those failure (except for the tooltips, the rest of the changes are to update the translations)

Tracking down the exact commit.

**Comment by jvillafanez** [comment]
Bisecting core changes, it looks like the commit that introduced the error is https://github.com/owncloud/core/commit/9489104cb3880f22d52bcf7b439a67dd3db60ccf . It also matches the time the tests started to fail.

**Comment by jvillafanez** [comment]
@DeepDiver1975 I guess the tests are failing because the users aren't synced in the account table. Any idea how we can fix this? (https://github.com/owncloud/user_ldap/blob/master/tests/User_LDAPTest.php#L398 as an example)

**Comment by DeepDiver1975** [comment]
Here is my quick analysis:
- testCheckPasswordPublicAPI: there is one method missing in the mock: getDisplayName. others most probaly as well. @jvillafanez please add the missing mock methods
- testGetUsersViaAPINoParam and others: these failing tests are quite expected. this is the changed behavior with oc10. Suggestion: either test the backend directly of force login on all test users to get them synced into the accounts table - most probably we need both
- testGetDisplayNamePublicAPI: this one needs a careful look - my assumption: this basically shows that we lost the feature of user name to uid transformation - which is strange - this should have been taken care of.

**Comment by jvillafanez** [comment]
PR in https://github.com/owncloud/user_ldap/pull/68

There are several things I don't like about the PR, but I don't have anything better at the moment. Mocking the whole account system in order to avoid the wiping out the account table each time seems quite expensive; and the logout shows some (suppressed) warnings about headers already been sent which can't be jumped over (unless we use other functions)
