### ISSUE TITLE
Update to 0.15.3 from 0.15.2 breaks user authentication

### ISSUE THREAD

**Issue by MascHman** [owncloud/user_ldap#661]
Hi,

we just upgraded from 0.15.2 to 0.15.3 and after successful upgrade our ldap users cannot login anymore. Using a fallback admin to log in, review the settings under User-Authentication -> LDAP reveals no errors whatsoever. All config tests are returning successful.

got some config logs of failed login attempts by my ldap user from that timeframe:

{"reqId":"onsmXM1u6idx5qqUaumP","level":2,"time":"2021-07-09T16:23:42+02:00","remoteAddr":"W.X.Y.Z","user":"--","app":"OCA\\User_LDAP\\User\\Manager","method":"POST","url":"\/index.php\/login?user=username","message":"No cached ldap result found for email_adress@domain.name"}
{"reqId":"onsmXM1u6idx5qqUaumP","level":2,"time":"2021-07-09T16:23:47+02:00","remoteAddr":"W.X.Y.Z","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=username","message":"Login failed: 'email_adress@domain.name' (Remote IP: 'W.X.Y.Z')"}
{"reqId":"onsmXM1u6idx5qqUaumP","level":2,"time":"2021-07-09T16:23:47+02:00","remoteAddr":"W.X.Y.Z","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=username","message":"Login failed: '11AE8D25-F1B0-49E4-9238-37837CAACD9E' (Remote IP: 'W.X.Y.Z')"}
{"reqId":"QPh32gmR0fPmJBSpSpoA","level":2,"time":"2021-07-09T16:24:12+02:00","remoteAddr":"W.X.Y.Z","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=email_adress@domain.name","message":"Login failed: 'username@domain.name' (Remote IP: 'W.X.Y.Z')"}

We're using an Active Directory as our LDAP backend and running on Windows 2016 Servers.
The Owncloud host itself is a standard Debian Linux (oldstable) running with PHP-7.4.21 , Apache 2.4.25

Is anyone else having this issue ?

I've downgraded our server back to 0.15.2 and everything is working again as before.

**Comment by jvillafanez** [comment]
Works for me in a basic docker setup (OC 10.7.0) and user_ldap updated from 0.15.2 to 0.15.3 against an AD inside a windows server 2016. PHP 7.4.3 and apache 2.4.41

@MascHman we'll need your OC server version and at least the ldap configuration. `occ config:list` should gather enough information (double-check any confidential information).
We might also need debug logs, although I'm not sure if there will be anything relevant.

You can also double-check with the latest docker image - 10.7.0 (https://hub.docker.com/r/owncloud/server/tags?page=1&ordering=last_updated)

**Comment by VicDeo** [comment]
could be related to special chars in password #662

**Comment by jnweiger** [comment]
@MascHman We will move ahead with #663 and hope that this was also the problem in your case. 
Please provide feedback, if you have more details.

**Comment by MascHman** [comment]
Hey, sorry for not answering in a timely manner. My desk is quiet full right now...

Thanks to everyone who took the time to answer to my issue!

@jvillafanez: Our Owncloud Version is the 10.7.0
This our config regarding the user_ldap app:
`"user_ldap": {
            "cleanUpJobOffset": "0",
            "enabled": "yes",
            "has_memberof_filter_support": "1",
            "home_folder_naming_rule": "attr:samaccountname",
            "installed_version": "0.15.2",
            "last_jpegPhoto_lookup": "0",
            "ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "ldap_attributes_for_group_search": "",
            "ldap_attributes_for_user_search": "",
            "ldap_backup_host": "ldaps:\/\/***REMOVED SENSITIVE VALUE***",
            "ldap_backup_port": "636",
            "ldap_base": "DC=***REMOVED SENSITIVE VALUE***,DC=***REMOVED SENSITIVE VALUE***",
            "ldap_base_groups": "OU=***REMOVED SENSITIVE VALUE***,OU=***REMOVED SENSITIVE VALUE***,OU=***REMOVED SENSITIVE VALUE***,DC=***REMOVED SENSITIVE VALUE***,DC=***REMOVED SENSITIVE VALUE***",
            "ldap_base_users": "***REMOVED SENSITIVE VALUE***",
            "ldap_cache_ttl": "300",
            "ldap_configuration_active": "1",
            "ldap_display_name": "displayname",
            "ldap_dn": "CN=***REMOVED SENSITIVE VALUE***,CN=Users,DC=***REMOVED SENSITIVE VALUE***,DC=***REMOVED SENSITIVE VALUE***",
            "ldap_dynamic_group_member_url": "",
            "ldap_email_attr": "mail",
            "ldap_experienced_admin": "1",
            "ldap_expert_username_attr": "",
            "ldap_expert_uuid_group_attr": "",
            "ldap_expert_uuid_user_attr": "objectguid",
            "ldap_group_display_name": "cn",
            "ldap_group_filter": "(&(|(objectclass=group))(|(cn=OC_User)))",
            "ldap_group_filter_mode": "0",
            "ldap_group_member_assoc_attribute": "member",
            "ldap_groupfilter_groups": "OC_User",
            "ldap_groupfilter_objectclass": "group",
            "ldap_host": "ldaps:\/\/***REMOVED SENSITIVE VALUE***",
            "ldap_login_filter": "(&(&(|(objectclass=person))(|(|(memberof=CN=***REMOVED SENSITIVE VALUE***,OU=***REMOVED SENSITIVE VALUE***,DC=***REMOVED SENSITIVE VALUE***,DC=***REMOVED SENSITIVE VALUE***)(primaryGroupID=10239))))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))",
            "ldap_login_filter_mode": "0",
            "ldap_loginfilter_attributes": "",
            "ldap_loginfilter_email": "1",
            "ldap_loginfilter_username": "1",
            "ldap_nested_groups": "0",
            "ldap_network_timeout": "10",
            "ldap_override_main_server": "0",
            "ldap_paging_size": "500",
            "ldap_port": "636",
            "ldap_quota_attr": "",
            "ldap_quota_def": "",
            "ldap_tls": "0",
            "ldap_turn_off_cert_check": "0",
            "ldap_user_display_name_2": "",
            "ldap_user_filter_mode": "0",
            "ldap_user_name": "samaccountname",
            "ldap_userfilter_groups": "OC_User",
            "ldap_userfilter_objectclass": "person",
            "ldap_userlist_filter": "(&(|(objectclass=person))(|(|(memberof=CN=OC_User,OU=***REMOVED SENSITIVE VALUE***,DC=***REMOVED SENSITIVE VALUE***,DC=***REMOVED SENSITIVE VALUE***)(primaryGroupID=10239))))",
            "signed": "true",
            "types": "authentication",
            "use_memberof_to_detect_membership": "1"
        }
`
I will try the latest docker-image to double check in a test environment, thanks.

@VicDeo : Good point, I will test it. The user I was having trouble with logging in, does not use a " char in its password, but other special characters.

**Comment by jvillafanez** [comment]
Passwords with `"` `'` `<` `=` `>` are affected. This is fixed with the linked patch (coming with the still unreleased 0.15.4 version). Note that most of the non-printable chars (except for the space) will still be removed, so you won't be able to log in if your password contains any of those characters.

**Comment by jnweiger** [comment]
Passwords with `"` `'` `<` `=` `>` should work again in user_ldap-0.15.4-rc3

**Comment by micbar** [comment]
@MascHman Can you confirm that v0.15.4 is working in your instance?

We have the 10.8.0 Release standing by, this is the last blocker.

**Comment by jnweiger** [comment]
@MascHman The latest docker with a potential fix is ready: `docker run --rm -ti -p 8080:8080 owncloud/server:10.8.0-rc1`

**Comment by MascHman** [comment]
Hey @jnweiger and @micbar ,

I've successfully tested the user_ldap-0.15.4-rc3 - thanks a lot.

Though I had to test in a cloned production environment, because within the docker container I was unable to install the app via "occ market:install -l PATH_TO/user_ldap-0.15.4-rc3.tar.gz . I got the errormessage "user_ldap: /mnt/data/user_ldap-0.15.4-rc3.tar.gz has the same or older version of the app." and could figure out why and how to resolve it.
Took a while longer to set-up, but now I can confirm the new release candidate is working in our environment.

**Comment by jnweiger** [comment]
Thanks for the report. Very much appreciated!

I also have issues wirh occ market:install -l I am afraid that is generally broken in newer server releases. Will investigate.


Am 17. Juli 2021 16:43:23 MESZ schrieb MascHman ***@***.***>:
>Hey @jnweiger and @micbar ,
>
>I've successfully tested the user_ldap-0.15.4-rc3 - thanks a lot.
>
>Though I had to test in a cloned production environment, because within
>the docker container I was unable to install the app via "occ
>market:install -l PATH_TO/user_ldap-0.15.4-rc3.tar.gz . I got the
>errormessage "user_ldap: /mnt/data/user_ldap-0.15.4-rc3.tar.gz has the
>same or older version of the app." and could figure out why and how to
>resolve it.
>Took a while longer to set-up, but now I can confirm the new release
>candidate is working in our environment.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/user_ldap/issues/661#issuecomment-881909263

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fraggy2k** [comment]
Hi Guys,

the final 0.15.4 release does not include the fix and the update via market breaks it again

**Comment by jvillafanez** [comment]
@fraggy2k it should be fixed now. If you installed the buggy version, you'll need to redownload and reinstall manually the package from the marketplace.
