### ISSUE TITLE
LDAP UI conflicts with OAuth app

### ISSUE THREAD

**Issue by JammingBen** [owncloud/user_ldap#668]
When having both apps `user_ldap` and `oauth2` enabled, the UI in the settings page looks messed up:

![image](https://user-images.githubusercontent.com/50302941/126483315-0f387bc1-aaa5-4334-b8f9-5da56fd26074.png)

Tested in Chrome and Firefox.

**Comment by hurradieweltgehtunter** [comment]
Please retest with latest state, this should already be fixed
