### ISSUE TITLE
User sync writes twice to account table

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#72]
### Steps

1. Setup LDAP and specify a user with an email address
1. Set a breakpoint in SyncService::run()
1. Run `occ user:sync 'OCA\User_LDAP\User_LDAP'`
1. Track it down into `processAttributes`

### Expected
`processAttributes` doesn't retrieve the account table's IUser entry.
It must return its own IUser instance that stores email, quota, etc.
It's the SyncService that uses these values then to populate the account table

### Actual
`processAttributes` calls `UserManager->get($uid)` and `$user->setEMailAddress()` which internally stores the email already into the account table.
Then later on the sync service does the same again. Or it skips it because the email didn't change.

### Versions
ownCloud 10.0 beta2+ master

While the end result might look the same, this makes problems with duplicate email addresses not solvable, see https://github.com/owncloud/core/pull/27652

**Comment by PVince81** [comment]
It's here https://github.com/owncloud/user_ldap/blob/v10.0.0beta2/lib/User/User.php#L451

This is all old behavior which is obsoleted by the account table.
A user backend shouldn't do such gymnastics to set email addresses or other values.

**Comment by PVince81** [comment]
@jvillafanez @DeepDiver1975 do we agree that any user backend should return its own implementation of IUser containing the necessary attributes ?

It should be possible here to make LDAP's `User` class actually implement `IUser` and have the getter/setters store into local attributes.

**Comment by PVince81** [comment]
Instead of implementing `IUser`, the backend should implement `IProvidesEmailBackend` and `IProvidesQuotaBackend`

**Comment by butonic** [comment]
fixed with https://github.com/owncloud/user_ldap/pull/125
