### ISSUE TITLE
The "recursiveMemberOf" group member algorithm doesn't work for all the cases

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/user_ldap#755]
Tested against an AD in a windows server 2019.

As far as I know, it happens with any new created user. The user is automatically member of the "Domain Users", which is member of the "Users" group.
The problem seems to be that the "Domain Users" membership for the new user is set as primary group id, and it isn't set explicitly as group membership. AD doesn't seem to follow the primary group id for a recursive member of search, so in practice, the new user won't be reported as member of "Domain Users" nor "Users" groups.

**Comment by jvillafanez** [comment]
The easiest solution would be to document the limitation in the UI

The other solution would be to get the primaryGroupToken of all the groups that are member of the target group in a recursive way. Having all those tokens, we get the users that are member of any of those primary groups.
The problem with this solutions is that we don't know how many groups we need to deal with. It could be ten, it could be thousands. The filter we need to build might be too long and could cause issues. In this case, we might need to split the filter and perform multiple queries, but we'd also need to take care of possible de-duplication.

**Comment by IljaN** [comment]
@pmaier1 ping

**Comment by NannaBarz** [comment]
@jvillafanez could you please document it? When we have a solution we can add it

**Comment by jvillafanez** [comment]
https://github.com/owncloud/user_ldap/pull/762 will add the notice in the ldap wizard. That should be good enough for the short term.

For the official documentation, we might need to schedule some time to recheck the content. The screenshots are old and some new stuff is missing. For this particular case, I don't think it's a big deal because the information is visible in the app.

**Comment by NannaBarz** [comment]
@mmattel could you please have a look what we need for the documentation?
