### ISSUE TITLE
AD objectsid attribute requires special handling

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/user_ldap#759]
The objectsid attribute from AD could be used as uuid attribute in the expert tab of the wizard. However, the attribute is binary and it's giving problems

The binary attribute should be transformed so it can be stored in the DB and shown in the logs.

**Comment by jvillafanez** [comment]
@d7oc

**Comment by d7oc** [comment]
@jvillafanez I think we can close this issue as well.
