### ISSUE TITLE
[10.Beta] User Administrator page still downloading 50 users per scrolling

### ISSUE THREAD

**Issue by cdamken** [owncloud/user_ldap#77]
So far I remember,  we talked that once we have the user Table (`oc_accounts`) we can sort the users and show them, if not all, at least a bigger amount and sorted.

Was I dreaming? or is still going to be in 10.0.1?

**Comment by cdamken** [comment]
@jvillafanez @PVince81 @butonic

**Comment by PVince81** [comment]
@felixboehm already suggested to do that and did some local testing. I don't remember the results.

**Comment by butonic** [comment]
the users are currently sorted by user_id, which may look unsorted if a uuid attributo has been used in user_ldap. regarding the amount of users loaded on the first batch: https://github.com/owncloud/core/pull/27715

**Comment by PVince81** [comment]
sorted where ? in users page ? (which is not very suitable for managing LDAP users) in share autocomplete ? (I thought searchByDisplayName would sort by display name)

**Comment by jvillafanez** [comment]
Just a minor clarification: LDAP won't return sorted results (might be possible, but completely discouraged). Sorting will happen in the account table, or on the client side.

**Comment by butonic** [comment]
https://github.com/owncloud/core/pull/27715 has been merged.
