### ISSUE TITLE
Acceptance tests are failing in Nightly in `BeforeScenario`

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/user_ldap#784]
Acceptance tests are failing in CI with
```
┌─ @BeforeScenario # FeatureContext::before()
      │
      ╳  Fatal error: Typed property FeatureContext::$skipImportLdif must not be accessed before initialization (Behat\Testwork\Call\Exception\FatalThrowableError)
```

Recently we did a big refactoring in core https://github.com/owncloud/core/pull/40754/files, so this might be one of the reasons behind this failure or it could be something else. Find out the issue and fix it.

Build link: https://drone.owncloud.com/owncloud/user_ldap/4499/67

**Comment by SwikritiT** [comment]
This issue and this issue https://github.com/owncloud/richdocuments/issues/490 might have a similar fix

**Comment by SagarGi** [comment]
Fixed by this PR https://github.com/owncloud/core/pull/40767
