### ISSUE TITLE
Prepare for publishing to market

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#79]
- [ ] unbundle from 10.0 release script (I'll take care of this)

- [ ] decide on version scheme. I suggest to go 0.10 until it's stable enough, then 1.0.
- [ ] build script that strips out unwanted stuff (ex: Makefile, could reuse https://github.com/owncloud/market/blob/master/Makefile)
- [ ] publish to market (as beta?)
- [ ] test updating

Changing the version scheme also means using that version number in the milestone tag, no more "10.0" or "10.0.1".

@jvillafanez @felixboehm @DeepDiver1975 @butonic

**Comment by jvillafanez** [comment]
This is solved from my point of view. Close?
