### ISSUE TITLE
Release user_ldap 0.18.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_ldap#792]
### Reasons

- Needed to go with server core 10.13 because of the Symfony 4 to 5 upgrade https://github.com/owncloud/core/issues/39630
- PR #787 made code changes needed for Symfony 5

Note: the change in that PR also works fine with server core 10.12 and before, so there should be no need to bump the core min-version.

The app can be released any time before 10.13 - it should work fine with any of the recent oC10 core releases.

**Comment by jnweiger** [comment]
https://github.com/owncloud/user_ldap/releases/download/v0.18.0-rc.1/user_ldap-0.18.0-rc.1.tar.gz

**Comment by jnweiger** [comment]
## Bugfix testing
* [x] #800
  - [ ] dns name of host can be used to derive Base DN
  - [ ] DN of User DN can be used to derive Base DN
  - [x] email addr of UserDN can be used to derive Base DN

QA passed with both core 10.12.2 and 10.13.0-alpha.1

**Comment by jnweiger** [comment]
Release done as part of 10.13.0
