### ISSUE TITLE
[10.0] Unknown behaviour between accounts table and LDAP user remnants

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/user_ldap#80]
The LDAP cleanup job will likely put LDAP users in the remnants table (as soon as it detects the users aren't in LDAP any longer).

The occ user:delete command is expected to remove the account for the user. What happens when the user's account is removed?

How both system interact with each other? It's not clear how the admin can remove the users from the remnants table

**Comment by PVince81** [comment]
Is the remnants table still required ? Maybe oc_accounts could have a flag about deleted users ?

Or not even that. Last time you said that when syncing users the command would output a list of deleted users which somehow matches what remnants would be. Then the admin can delete these users individually.

And yes have occ user:sync --delete would be better, did you make a ticket in core for that ?

**Comment by jvillafanez** [comment]
> Is the remnants table still required ? Maybe oc_accounts could have a flag about deleted users ?

Probaly not. Accounts should be able to handle this somehow.

> And yes have occ user:sync --delete would be better, did you make a ticket in core for that ?

https://github.com/owncloud/core/issues/27702

**Comment by PVince81** [comment]
Ok, so let's use this ticket here as "kill remnants table"

**Comment by jvillafanez** [comment]
This can be closed. https://github.com/owncloud/user_ldap/pull/85 is merged.
