### ISSUE TITLE
Bad UX: No submit button and extra occ:sync command needed. 

### ISSUE THREAD

**Issue by JKawohl** [owncloud/user_ldap#82]
When entering LDAP configuration i would expect that at the end there would be a submit button 

![bildschirmfoto 2017-04-24 um 14 32 33](https://cloud.githubusercontent.com/assets/12275313/25337196/25b57570-28fb-11e7-999a-9e1d12e3a875.png)

That triggers the occ:sync with the corresponding wrapper. So users show up  in the users list directly after the submit button was clicked. 

![bildschirmfoto 2017-04-24 um 14 56 03](https://cloud.githubusercontent.com/assets/12275313/25338056/3eccdcbc-28fe-11e7-9565-8e55e295333e.png)

Currently the app gives no feedback and there is no mention to do an occ:user sync . From my point of view this is absolutely not intuitive and will cause a lot of tickets and misconfigurations while people try to get this to work without knowing about the user sync command. 

@cdamken 
@felixboehm 
@michaelstingl 
@pako81

**Comment by PVince81** [comment]
Submit button is duplicate of https://github.com/owncloud/user_ldap/issues/27.

But I agree that the UI should probably have links to the documentation about user:sync

**Comment by PVince81** [comment]
triage

**Comment by felixboehm** [comment]
duplicate
