### ISSUE TITLE
[QA] Exposed User Attributes must be written all lower case

### ISSUE THREAD

**Issue by jnweiger** [owncloud/user_ldap#820]
Seen in user_ldap-0.19.0 with windows_network_drive 2.4.0 and core 10.13.0

* The ldap schema has:
```
ldapsearch -x -H ldap://$ldapserver -b dc=owncloud,dc=com -D "$admin_dn" -w "$admin_pass" '(uid=lemming0123)'
...
   uidNumber: 20123
   gidNumber: 30000
   homeDirectory: alice
   ownCloudUUID: 8ce67d3a-3079-4755-a7df-6ef77ac2b8c8
```

* in Admin -> Settings -> User Authentication -> Advanced
   we want to allow the `homeDirectory` attribute as an Exposed Attribute  
![grafik](https://github.com/owncloud/user_ldap/assets/1108546/61e124d3-0627-4bd1-a3ee-c5a0b740ddbc)
----
* in config.php we want to (mis)use the `homeDirectory` attribute to map the uid lemming0123 to Alice:
  ```
    'wnd.kerberos.servers' => [
        'ad01_lem' => [         /* <--- kerberos data id */
            'ockeytab' => '/etc/apache2/oc20230731.keytab',
            'ocservice' => 'HTTP/oc10130a1-kerberos-100rc3-20230801.jw-qa.owncloud.works',
            'usermapping' => ['type' => 'EALdapAttr', 'params' => ['attr' => 'homeDirectory']],
            'ccachettl' => 3600,
        ],
  ```
  
* In Admin -> Storages, we mount a WND drive using the `ad01_lem` data ID
![grafik](https://github.com/owncloud/user_ldap/assets/1108546/14f5c3ff-c12c-4c34-bbdf-93cb8012b890)
----
* (Optionally) patch the error message windows_network_drive/lib/kerberos/usermappings/ealdapattr.php to include more details:
```
			throw new MappingException('Requested attribute not found or not exposed: ' . $this->attr . " -> " . serialize($eas));
```
* When user lemming01234 wants to access their `lemming-wnd` folder, an error occurs:
![grafik](https://github.com/owncloud/user_ldap/assets/1108546/248981ed-aec0-42a7-9af7-920b6efde7e6)
----

### Expected behavior
* LDAP Attibutes can be spelled as is.
* LDAP Attribute names are case insensitive.

### Workaround
* Spell `homedirectory` in all lower case in Admin -> Settings -> User Authentication -> Advanced -> Exposed Attribute
* Now the error no longer happens.

**Comment by jvillafanez** [comment]
Fix on the WND side -> https://github.com/owncloud/windows_network_drive/pull/472 . As said in the PR, it's targeting the release branch.

It makes more sense that WND matches whatever LDAP is exposing.

**Comment by jnweiger** [comment]
Confirmed fixed with https://github.com/owncloud/windows_network_drive/pull/472 -> windows_network_drive-2.4.0-rc.2
Also lower case works. The Attribute name must be written consistently either both upper case or both lower case, in user_ldap advanced settings and windows_network_drive config. OK.
