### ISSUE TITLE
Build script / Makefile for marketplace releasing

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#83]
Easiest would be to reuse https://github.com/owncloud/market/blob/master/Makefile

@jvillafanez

**Comment by DeepDiver1975** [comment]
I'm reopening this since the app cannot be uploaded to be marketplace:
- [ ] get a signing key
- [ ] add category to info.xml @pmaier1 where shall we put it?
- [ ] a screenshot has to be added to info.xml
- [ ] test it on marketplace.int.owncloud.com

**Comment by pmaier1** [comment]
> add category to info.xml @pmaier1 where shall we put it?

'Integration' I would say.

**Comment by pmaier1** [comment]
see [here](https://github.com/owncloud/marketplace/issues/85) in general ;)

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
@jvillafanez can we finish this ? As I understand the LDAP app should be available in the market when 10.0.1 is out. Best would be to have it a bit earlier for testing (staging)

**Comment by jvillafanez** [comment]
Makefile is already merged, so I guess this can be closed unless there are modifications to be made there.

**Comment by PVince81** [comment]
@jvillafanez were these items handled ? https://github.com/owncloud/user_ldap/issues/83#issuecomment-299150776

**Comment by PVince81** [comment]
@jvillafanez ping

**Comment by jvillafanez** [comment]
I have my key and I can upload the package in the internal marketplace. I don't know if we should share the key so you can upload it to the internal marketplace if I'm out. Anyway, I don't expect to upload the app to the official marketplace.

**Comment by jvillafanez** [comment]
Makefile ready and app uploaded. Closing.
