### ISSUE TITLE
User Home Folder Naming Rule with common values for different users does not update the files from other accounts

### ISSUE THREAD

**Issue by davitol** [owncloud/user_ldap#90]
### Steps to reproduce

1. Set an LDAP configuration in the wizard and set as  User Home Folder Naming Rule a field with same valu for several users (e.g. cn in my LDAP backend)
2. Login with user aaliyah_adams that has cn = aaliyah and upload a fileA
3. Login with user aaliyah_beer that has cn = aaliyah and upload a fileB

### Expected behaviour

aaliyah_adams should be able to see fileB

### Actual behaviour

fileB is not shown in aaliyah_adams account

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.12"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
WebDAV

**Are you using encryption:** 
No

**Logs**

Server Logs

```

```

### Client configuration

**Browser**

Mozilla

@jvillafanez

**Comment by jvillafanez** [comment]
This is a core issue regarding the FS update detection. While this is triggered by the user_ldap app, there is nothing the app can do about it other than try to prevent this scenario from happening; to be decided how if we want to tackle this.

**Comment by davitol** [comment]
Tested in oC "10.0.4 RC1" and works fine. So it is fixed.
